### ISSUE TITLE
Inverted subtones are not read correctly in the scan function(*) or FC(4)

### ISSUE THREAD

**Issue by Svistag** [egzumer/uv-k5-firmware-custom#102]
For ex subtone D734I is read as D371N or D255I as 136.5Hz

**Comment by ErikS-web** [comment]
Please some more info. Can you test what is good and what is wrong. And explain how you tested.

**Comment by egzumer** [comment]
They are read correctly, search on the internet what are inverted subtones.

**Comment by egzumer** [comment]
Ok, the second one is a bug, but there is nothing I can do about it. This is what the RF module return, there is some issue there.
