### ISSUE TITLE
Scan list retention

### ISSUE THREAD

**Issue by TokeTokerson** [egzumer/uv-k5-firmware-custom#107]
Hello, appreciate all the upgrades thus far. The improved mic tx bar is a nice quality of life touch. Was wondering if the scan list selections can be retained upon turning the radio on. I've noticed that it defaults to scan list I instead of II or all memory channels when turning the radio off them on. 
- Thanks!

**Comment by ErikS-web** [comment]
When you EXIT from the scan, the scan list setting is remembered
At Power-On is indeed list-1

Tip. Long press `SCAN` while channel scan is in progress, toggles scan lists 1/2/ALL(presented as *)

**Comment by ErikS-web** [comment]
With Chirp you can adjust the default scan list.

![Knipsel](https://github.com/egzumer/uv-k5-firmware-custom/assets/148579604/9b5901ba-5757-4acd-bc32-b6f67c6c3ee2)

Can you test that and report back the result?

**Comment by ErikS-web** [comment]
In Menu the parameter can be set with 19. `SList` - _selects which channel is used by memory channel scanner_
