### ISSUE TITLE
AM fix doesn't work in spectrum analyzer

### ISSUE THREAD

**Issue by Robby69400** [egzumer/uv-k5-firmware-custom#113]
Hello,
when i'm listening an air frequency in AM, the sound is good, but if I switch to spectrum and select AM, 
sometimes its OK sometimes unreadable. 
I think it happens especiallly with strong signals.
AM fix is activated

**Comment by ErikS-web** [comment]
Can you add a foto ?

**Comment by chouyu** [comment]
It  seems like AM-fix is not activated in spectrum mode.

**Comment by ErikS-web** [comment]
Problem is the same as initiated from Discussions.

Will close this Issue. Pse continue under #118

**Comment by egzumer** [comment]
The AM fix indeed doesn't work in the spectrum analyzer, it never did. This is something that needs to be worked on.

**Comment by DL4SDR** [comment]
Hi, hmmm....AM  in AIRBand     in 0.15   works  here. actually  listening with 2 Radio's....one in VFO Mode, one in Spectrum-Mode
The Audio-Quality in Spectrum Mode  is not so good as in VFO Mode but readable  to identify everthing

**Comment by jh4vaj** [comment]
It appears that reducing the LNAs/LNA/PGA appropriately can enable normal AM demodulation, in spectrum analyzer mode. 
I found this information on Twitter (X) (in Japanese), and it worked well with v0.19.

https://twitter.com/jr3kqf/status/1730911248001413373
