### ISSUE TITLE
improvement-make monitor mode independent on PTT

### ISSUE THREAD

**Issue by pawol** [egzumer/uv-k5-firmware-custom#114]
improvement-make monitor mode independent on PTT. At the moment the PTT cancels monitor mode.

**Comment by ErikS-web** [comment]
What monitor mode ?

I can only think of.. but that functions reversed.....

- PTT enters detail monitor mode when Spectrum-analyzer is active.

**Comment by pawol** [comment]
I am talking about normal mode.  For me, the  spectrum is a gadget only. I do not compile it.

**Comment by ErikS-web** [comment]
Aha you mean when the Monitor function is set under Custom Button 1 or 2.
Well this functions for **VFO.**

But there is a difference
When monitor is set open on a **Memory channnel**. Than is stays open after TX.
This is NOT on original firmware.

If you prefer continuously Open Monitor on VFO
Set squelch to 0 with
Menu option 60 `Sql` - squelch sensitivity level (0=OFF/1 .. 9)

**Comment by pawol** [comment]
The issuevis not to set sql=0. It works in  way I described on 1of11 builds but last time his build are extremally bugged and cannot repport issues :(

**Comment by ErikS-web** [comment]
Than use VFO-mode for now.

**Comment by pawol** [comment]
VFO the same, PTT cancels monitor mode

**Comment by pawol** [comment]
BTW. Squelch=0 makes monitor mode. No difference but much quicker

**Comment by ErikS-web** [comment]
My testing that it worked with VFO was not correct. 
Squelch (re)opend due to QRM/interference from PC.

**Comment by pawol** [comment]
So we have a bug

**Comment by ErikS-web** [comment]
Yes, thats why I made that a separate issue.

I think it would be better to interpret your request as a request for an extension to Monitor mode.
Mode 0 behaves as set Squelch = 0. 
Mode 1 the current behavior: Squelch open but back to old level when TX is pressed.
