### ISSUE TITLE
demodulator mode Lock

### ISSUE THREAD

**Issue by bonnerglp** [egzumer/uv-k5-firmware-custom#115]
AM mode for air band is not persistent for memory channel. Is there a way to lock a channel in AM mode?

**Comment by ErikS-web** [comment]
Could you check this setting in Chirp, under Mode for each channel.

**Comment by bonnerglp** [comment]
That was it. They were in FM. Changed to AM and now locked-thanks

**Comment by ErikS-web** [comment]
Happy to help you, enjoy the hobby ;-)
