### ISSUE TITLE
MDC 1200

### ISSUE THREAD

**Issue by Zahurzahur** [egzumer/uv-k5-firmware-custom#117]
Can we add MDC 1200 in version 0.17? 
Tx(ing) like Motorola.
If there is space isue ,is it possible to  FW 0.17?  as like Bricky has converted the FW into 43.6 kb . I want to do that, plz guide me that is possible or not.

Bricky says:
There's talk of the latest ARM toolchain reducing the size of firmware by under 1KiB. It's nice, but I think I've got the smallest firmware already.
13.2, GNU Linux. I use GCC 13.2 anyway so it's no big deal for me.

41.9K, but the recent MDC1200 port increased it to 43.6K.

**Comment by pawol** [comment]
useless feature.

**Comment by ErikS-web** [comment]
Who is **Bricky** ? Please help us and point us with an URL ?

Always interesting to watch.
But I do wonder in advance to what extent the performance is affected by the compression.

**Comment by ETO-bigbang** [comment]
MDC1200 is very useful for exchanging information with more HAMs, and MDC can be used as an optional feature. If necessary, you can compile it yourself

**Comment by Zahurzahur** [comment]
> Who is **Bricky** ? Please help us and point us with an URL ?
> 
> Always interesting to watch. But I do wonder in advance to what extent the performance is affected by the compression.

You can find it in contributers in this page as Bricky149

**Comment by rai4424** [comment]
> useless feature.

Useful for motorolla users. We can able to use Uvk5 in group that is using motorollas.

**Comment by ErikS-web** [comment]
> > Who is **Bricky** ? Please help us and point us with an URL ?
> > Always interesting to watch. But I do wonder in advance to what extent the performance is affected by the compression.
> 
> You can find it in contributers in this page as Bricky149

Please help us and point us to the information you mean with a URL?

Would be nice if you explain the difference.

**Comment by var-tz** [comment]
very useful for  HAMs, the MDC1200 sound  especially easy to tell from noise.

**Comment by egzumer** [comment]
I don't plan to add MDC1200. This is way to much effort for way to little gain. This is a really niche feature. If you just want the sound turn on the MDC in the Roger menu.

**Comment by ETO-bigbang** [comment]
> I don't plan to add MDC1200. This is way to much effort for way to little gain. This is a really niche feature. If you just want the sound turn on the MDC in the Roger menu.

The MDC sound in the Roger menu sounds very fake. MDC1200 can be used as an optional feature, and HAM can compile it!

**Comment by egzumer** [comment]
So what it sounds fake? Why do you want it to sound legit?
