### ISSUE TITLE
vfo input hide information

### ISSUE THREAD

**Issue by CaptainRi** [egzumer/uv-k5-firmware-custom#125]
In VFO mode, the upstream input frequency screen will hide other information, while in downstream input frequency, this phenomenon will not occur
<img src="https://github.com/egzumer/uv-k5-firmware-custom/assets/67640429/2b99933f-daf5-4f1e-9771-018dca0c028f" width=350><img src="https://github.com/egzumer/uv-k5-firmware-custom/assets/67640429/ab86879d-a08e-4b42-b51e-396bdc019e13" width=350>

**Comment by ErikS-web** [comment]
Thanks for reporting it. Maybe it can be remedied.
It is special that it only happens with VFO and not with a memory channel,

Does this lead to a malfunction?

It is only when entering a new frequency.
The secondary channel can receive while you type a new frequency on the primary channel.
At this time, the RX is not displayed and only the signal strength of the S-meter of the signal reception on the secondary channel is displayed.

Refresh of the display content, perhaps not optimal at that moment.
But once the new frequency entry is completed, everything is fine. In my opinion.
