### ISSUE TITLE
The main interface is chaotic and automatically jumps to 1300MHZ for monitoring

### ISSUE THREAD

**Issue by wu58430** [egzumer/uv-k5-firmware-custom#129]
I previously used other customized systems. Before shooting this video, I burned the official system for a full reset, and then burned your system for a full reset. This video describes the problem I encountered.
Strangely, then I couldn't see any options in the 13th menu item (Demodu)
Thank you very much for your work
https://github.com/egzumer/uv-k5-firmware-custom/assets/52628935/2d9d8608-b434-4c32-af01-9fb1467f1c1e

**Comment by wu58430** [comment]
I am using version 0.17
I wonder if this is related to the gEeprom section

**Comment by egzumer** [comment]
What do you mean by "burned the system for a full reset", burning firmware doesn't reset anything.

**Comment by wu58430** [comment]
> What do you mean by "burned the system for a full reset", burning firmware doesn't reset anything.

What I mean is to reset the system in the 69th menu after burning it

**Comment by ErikS-web** [comment]
Menu 69 has 2 options... Please be more specific.

![Knipsel](https://github.com/egzumer/uv-k5-firmware-custom/assets/148579604/b0f469fa-6d3b-471d-b12d-b1c253bb5002)

**Comment by wu58430** [comment]
> Menu 69 has 2 options... Please be more specific.
> 
> ![Knipsel](https://user-images.githubusercontent.com/148579604/284661147-b0f469fa-6d3b-471d-b12d-b1c253bb5002.JPG)

anyone

**Comment by wu58430** [comment]
[

https://github.com/egzumer/uv-k5-firmware-custom/assets/52628935/3adb2841-ff60-4b68-a024-88bc15d9e05e

](url)
