### ISSUE TITLE
Allow to scan range of frequencies

### ISSUE THREAD

**Issue by artyom-smirnov** [egzumer/uv-k5-firmware-custom#132]
Original firmware allows scan only entire band. I think it will be neat feature to scan band partially.

Example:

https://baofengtech.com/scan-a-range-of-frequencies-with-your-uv-5x3/

**Comment by egzumer** [comment]
See how that works for you. You need to set upper and lower frequency as beginning and end of a scan range. Long press 5, long press *.
https://github.com/egzumer/uv-k5-firmware-custom/suites/18540315300/artifacts/1076405937

**Comment by egzumer** [comment]
Fixed by force push

**Comment by egzumer** [comment]
It does not, but there were other changes that raised the memory usage.

**Comment by artyom-smirnov** [comment]
That was fast. Thanks! Found minor bug in UI with scan range (#158)
