### ISSUE TITLE
add text messaging

### ISSUE THREAD

**Issue by mikhailsimon** [egzumer/uv-k5-firmware-custom#136]
Hi, I've seen other mods that have text messaging over AFSK..do you think its possible to implement or the flash storage isn't enough

**Comment by ErikS-web** [comment]
DTMF is supported in radio.
In my opinion, other digital things should be accomplished externally on a PC. And to make this possible, this issue has been submitted [See #90](https://github.com/egzumer/uv-k5-firmware-custom/issues/90)

**Comment by harifhaqim** [comment]
DTMF is for calling but text messaging on QS itself is pretty handy since it's portable....DTMF does support numbers and A-D only... it's doesn't support whole alphabet and spaces

**Comment by JollyH0789** [comment]
The messages are useless, better to put other more interesting functions

**Comment by ErikS-web** [comment]
Out of curiosity, a few questions.
Which characters must be supported? All ISO-8859 and ISO-2022 and more icons such as smilies ;-)
Please note that everything must fit into 60KB!
The next question is the method of input.
Seems very clumsy on such a small keyboard?!
