### ISSUE TITLE
bug - fm modulation has no FM mark on display

### ISSUE THREAD

**Issue by pawol** [egzumer/uv-k5-firmware-custom#137]
when fm modulation is set then there no FM mark on display

**Comment by JollyH0789** [comment]
yes, I would also like the FM symbol always visible on the display

**Comment by ErikS-web** [comment]
It's bij default FM, unless other signalled on the display.

And in those situations only reception/RX.

**Comment by pawol** [comment]
Simply this is a bug

**Comment by egzumer** [comment]
This is an FM transciever. The other modulations are an extra options, a hack, that also disable TX, that is why those are displayed. FM is a default mode, there is no point in showing that.

**Comment by pawol** [comment]
You are wrong. This Is also AM receiver by default
