### ISSUE TITLE
Help to makefile

### ISSUE THREAD

**Issue by rai4424** [egzumer/uv-k5-firmware-custom#14]
How can I save the changes in makefile .I want to make my custom bin file for myself.

**Comment by egzumer** [comment]
Depends on what you mean, the direct answer is you open the Makefile file, you make modifications, and you save it (possibly CTRL+S). Then you compile the software, voilà.

To actually save the changes you create a branch on the local repository and merge changes from time to time.

**Comment by rai4424** [comment]
A lot of thanks
