### ISSUE TITLE
Add a option to put Personalized TEXT in Welcome screen

### ISSUE THREAD

**Issue by MachoEnLaNoche** [egzumer/uv-k5-firmware-custom#140]
Hello. Will be very useful to indentify the walkie talkie in companys or groups o personal use owner.
To put an option to enable add your Own text in the welcome screen below the voltage, or the wellcome.
Please add option in menu, to edit it!
Very useful to put our Name, hamradio license number...

**Comment by ErikS-web** [comment]
What modulation ?

This radio can only TX in FM.

**Comment by MachoEnLaNoche** [comment]
> You can Adjust the welcome screen with Chirp ![Welcome](https://user-images.githubusercontent.com/148579604/285465137-023d524b-7947-4611-bfa1-8b5dc8a3eb9e.jpg)

Thanks for the info.
But it will better if it can be modifided from menu.
Thanks for your work!

**Comment by ErikS-web** [comment]
On the PC with Chirp it takes less than 90 seconds work.
And after that I never changed it again. 

So why waste memory-space on the modify-function; the radio only has 60kB. 
That choice keeps coming back.

**Comment by ErikS-web** [comment]
change 34. `POnMsg` - power on message, to value MESSAGE 

and use Chirp to set the Settings. Just like the above show lines.

And your screen shows

![egzumer - display](https://github.com/egzumer/uv-k5-firmware-custom/assets/148579604/0ee03884-c7c3-4346-b338-15c9e8abd991)

**Comment by MachoEnLaNoche** [comment]
[https://youtu.be/wcS0kTk3DUc](url)

**Comment by ErikS-web** [comment]
Have FUN with your HAM-hobby 
.
![Knipsel](https://github.com/egzumer/uv-k5-firmware-custom/assets/148579604/b733a6b0-8826-4508-9e85-b5731ecc3490)
