### ISSUE TITLE
Tx on Air Band

### ISSUE THREAD

**Issue by Giagio89** [egzumer/uv-k5-firmware-custom#142]
Hello! Thanks a lot for you wonderfull work. I have an aviation license so I can broadcast on aviation bands. What are the parameters that need to be modified (in the code) to be able to speak on those frequencies? Obviously at my own risk

**Comment by ErikS-web** [comment]
What modulation ?

Remender that this radio only does FM wih TX.

**Comment by Giagio89** [comment]
Thx for aswer.
On AM.
 With this firmware (https://whosmatt.github.io/uvmod/) I could transmit.

**Comment by ErikS-web** [comment]
Only RX, no TX.

**Comment by f5gkw** [comment]
IMHO, don't use this radio on airband despite you have a licence to do.
It is not only your risk, it is also risks for others users as this radio
is full of harmonics.

**Comment by ErikS-web** [comment]
Suggest to read this.... https://en.wikipedia.org/wiki/Airband

**Comment by egzumer** [comment]
Harmonics are not a problem on those frequencies. The lack of AM modulation is. If you want to transmit on airband buy a proper airband radio. Airband communication is a serious thing, I'm not going to help you to spam on that band. Sorry.
