### ISSUE TITLE
In spectrum mode, after deleting the decimal point, it is not possible to input the decimal point again

### ISSUE THREAD

**Issue by wu58430** [egzumer/uv-k5-firmware-custom#148]
In spectrum mode, press 5 to input the frequency. If the decimal point is removed, it will no longer be possible to input the decimal point. Exiting the input state and then re-entering can solve this problem. I tried using the following modifications to solve this problem（in spectrum.c ）:

![图片](https://github.com/egzumer/uv-k5-firmware-custom/assets/52628935/4bdce062-e6dc-43cc-8e6c-1ec10e4ad92d)

So far, it has been working very well!
Thank you for your work!!!

**Comment by ErikS-web** [comment]
I can reproduce this.

**Comment by wu58430** [comment]
> I can reproduce this.



> I can reproduce this.

Yes, your execution ability is very strong. This is just a small issue. Thank you very much for your work
