### ISSUE TITLE
Why is there no 1750 tone

### ISSUE THREAD

**Issue by bh2rmx** [egzumer/uv-k5-firmware-custom#165]
ver  0.19

**Comment by egzumer** [comment]
There is read the manual

**Comment by f5gkw** [comment]
I also don't find the 1750Hz option to add to a shortkey .
looks to be disabled :
https://github.com/egzumer/uv-k5-firmware-custom/commit/44ff33613ab389525661d623e36c973901af50ff

TU, 73 !

**Comment by egzumer** [comment]
https://github.com/egzumer/uv-k5-firmware-custom/wiki/Radio-operation#1750-hz-toneburst-for-repeater-access
