### ISSUE TITLE
CTCSS disappear

### ISSUE THREAD

**Issue by losehu** [egzumer/uv-k5-firmware-custom#166]
In the main interface, one of my channels originally had CT display, but after switching to AM and then back to FM, the CT disappeared

**Comment by egzumer** [comment]
This is a feature that I will probably delete. It comes from 1o11 repo. The presumption is probably that CTCSS is not supported in AM.

**Comment by losehu** [comment]
> This is a feature that I will probably delete. It comes from 1o11 repo. The presumption is probably that CTCSS is not supported in AM.

Thank u very much for ur work!
