### ISSUE TITLE
SPectrum issues

### ISSUE THREAD

**Issue by lohtse** [egzumer/uv-k5-firmware-custom#185]
As of Todays changes I can nolonger changes reg/settings in spectrum after pressing PPT on an FRQ then menu to adjust regs etc... Only the IF one works sort of....

Just letting you know

**Comment by pawol** [comment]
probably auto adjustment of am fix locks parameters. That makes sense

**Comment by egzumer** [comment]
Yes that is the reason. I will probably disable AGC if those values are changed manually.

**Comment by pawol** [comment]
ticked to close

**Comment by pawol** [comment]
Make sense. I suspect when AM fix is disabled in the menu
then manual adjustment is possible. The main question is for what to do it :)
