### ISSUE TITLE
Transmit Ton / Alarm on/off will not run

### ISSUE THREAD

**Issue by tuvok81** [egzumer/uv-k5-firmware-custom#196]
Hey ho .. 
a Question .. 
on Key 1 short press is the transmit Ton 1750 Hz
on Key 2 long press is the Alarm on/off 

but this 2 Keys will not run for me on my 2 Devices.. 

![grafik](https://github.com/egzumer/uv-k5-firmware-custom/assets/30367063/5be644f6-77f3-4982-9726-22bf609309ec)

**Comment by egzumer** [comment]
https://github.com/egzumer/uv-k5-firmware-custom/wiki/Differences-from-QS-stock-firmware
