### ISSUE TITLE
Memory with frequency between 300Mhz and 400mhz moves to 433.00Mhz.

### ISSUE THREAD

**Issue by iu0azb** [egzumer/uv-k5-firmware-custom#202]
Hello,
as mentioned in discussion entry, I'm a fan of your firmware.. but today I finally recognize a bug that apparenty modify any memory with 300-400mhz frequency stored to 433.000Mhz, still keeping all rest of parameter, tex tag included.
To doublecheck I've  reloaded with chirp the memories with no changes on the radio.. Using the original firmware or the IJv one, the memories back to correspond with what loaded :)
I'm not exacly sure if the frequency range is exaclty that one reported above but it should be close to it. 
Luca

**Comment by iu0azb** [comment]
It's really strange.. just tried again and it seem that the memory is correctly wrote but when scrolling the list from radio I still readt 433.00 instead the real freq.. not sure why. If it's just an isolated issue on my radio, thats'it :) .. but I would reccomend to spread the verification to other users. 
Thanks for your prompt react

**Comment by iu0azb** [comment]
[UV-K5_20231201.zip](https://github.com/egzumer/uv-k5-firmware-custom/files/13598818/UV-K5_20231201.zip)

**Comment by iu0azb** [comment]
If you remember the band limit you think, I can verify if the issue is strictly related to that.

**Comment by egzumer** [comment]
You have 350MHz band disabled in the hidden menu.

**Comment by iu0azb** [comment]
Yeap.. enabling it fixed the issue. 🙏
