### ISSUE TITLE
DTMF whilst receive airband?

### ISSUE THREAD

**Issue by kittenarmy** [egzumer/uv-k5-firmware-custom#204]
Using v19. Not sure if this is a bug but I didn't notice it before in other firmware. I get this string appearing sometimes whilst receiving, not pressing any buttons or hearing any DTMF tones.

![MVI_0881 - frame at 2m22s](https://github.com/egzumer/uv-k5-firmware-custom/assets/9025713/d7cca02c-a84a-4011-aed3-ac61b42d73e6)

![MVI_0881 - frame at 2m37s](https://github.com/egzumer/uv-k5-firmware-custom/assets/9025713/202abff1-678c-478c-98fb-e96b3e5d457c)

Video clip:
https://imgur.com/a/stgPudN

**Comment by egzumer** [comment]
It is how it works. It takes noise for DTMF codes, this is how the RF chip works. The live DTMF isn't really useful and probably should be deleted from default build. It can also be disabled in the menu.

**Comment by kittenarmy** [comment]
Ahh thank you!
