### ISSUE TITLE
Spectrum problem

### ISSUE THREAD

**Issue by weidong0911** [egzumer/uv-k5-firmware-custom#207]
Hello I encountered an interesting issue with this firmware (https://github.com/egzumer/uv-k5-firmware-custom/actions/runs/7122071786). In spectrum mode, pressing the number key 1 adjusts to 100K, and pressing 4 adjusts to 128X. However, when I input a frequency like 460.000 using the number key 5, the spectrum only shows signals between XXX.000-XXX.900. Similarly, if I input 460.125, the spectrum only displays signals between XXX.025-XXX.925. Other signals are neither visible nor audible, but this works fine in AM mode.

**Comment by g4eml** [comment]
That is expected behaviour. If you set 100KHz with Key 1 then the radio only listens in steps of 100KHz. Any signals in between those steps will not be heard. If you want to ensure you see all signals you should not set a step larger than the expected channel spacing.

**Comment by weidong0911** [comment]
> 这是预期的行为。如果您使用键 1 设置 100KHz，则收音机仅以 100KHz 为步长收听。这些步骤之间的任何信号都不会被听到。如果您想确保看到所有信号，则不应设置大于预期通道间距的步长。

Thank you for your reply. I understand now, and it has relieved my concerns. Thanks again.
