### ISSUE TITLE
Frequency, invalid edit (Chirp)

### ISSUE THREAD

**Issue by pietss** [egzumer/uv-k5-firmware-custom#210]
I apologize for the question which is perhaps trivial but I didn't understand what the problem is, which probably comes from Chirp.
It seems that using Chirp it is not possible to memorize the frequencies ranging, approximately (the range could be greater), from 77.00 to 79.00
In chirp I checked the box: Setting: Driver information: Limit disabled for modified firmware; but the window appears saying: Invalid edit: frequency [….] is of out of supported range….
Can this be resolved somehow? 
Many thanks

**Comment by Arikshten** [comment]
It looks like there is already work being done on adding an appropriate memory map to Chirp 

https://github.com/egzumer/uv-k5-firmware-custom/discussions/183

This might resolve any issues.
