### ISSUE TITLE
RX issue

### ISSUE THREAD

**Issue by lohtse** [egzumer/uv-k5-firmware-custom#211]
As of the time this was posted I now have an issues when receiving as seen in video... It happens with most AM frgs I have stored... I also now have random lock ups with Spectrum.... TI recompiled using you default and my preferred Setup and both have the same issues... Yesterdays Comipled version did not suffer from the issues BTW

https://github.com/egzumer/uv-k5-firmware-custom/assets/48331155/636557c2-568f-4b40-81a3-96873668254e

PS volume in the radio is almost full....

**Comment by egzumer** [comment]
This is a work in progress, I don't know which version you used.
Try this https://github.com/egzumer/uv-k5-firmware-custom/actions/runs/7129077228

**Comment by egzumer** [comment]
I still don't know which...

**Comment by egzumer** [comment]
> This is using c9ff301

I never pushed any commit with such SHA-1
https://github.com/egzumer/uv-k5-firmware-custom/actions

**Comment by AsciiWolf** [comment]
I have experienced lockups when in spectrum analyzer mode only with strong air band signals.

**Comment by egzumer** [comment]
I pushed this commit 20minutes ago so you didn't test with that one when you reported the issue.
Does the problem persist with firmware form this github action: https://github.com/egzumer/uv-k5-firmware-custom/actions/runs/7129750771

(there is a firmware at the bottom)
