### ISSUE TITLE
Congratulations Mr. Egzumer!

### ISSUE THREAD

**Issue by rai4424** [egzumer/uv-k5-firmware-custom#22]
You deserve a lot of congratulations. Your tireless and selfless work has made me see something I have been wanting to do for a long time. Uv-k5 V0.9 best one till now. You turned a trivial thing into a precious thing.
Thankyou very much.

**Comment by Yag00000** [comment]
congrats Egxumer for this excelent work v0.9 !!

**Comment by egzumer** [comment]
Thanks.
