### ISSUE TITLE
no reception on the 2M band

### ISSUE THREAD

**Issue by MPHI77** [egzumer/uv-k5-firmware-custom#226]
I can no longer get any radio in the 2M band. The meter shows full reception, but there is nothing except noise. Unfortunately the problem only occurs with your mod. testet with 017,018,019.

**Comment by gartnl** [comment]
Did you make sure demodulation is set to FM? See menu 13.

**Comment by ErikS-web** [comment]
do you suggest that with firmware 16 it is ok ?

pse check...

13 `Demodu` - demodulator mode, default is **FM**, AM/USB can be used for listening only

**Comment by MPHI77** [comment]
Ok, I have to apologize. It was actually my fault. I had also tested the demodulation on FM, but didn't think about it when I turn the radio off and on again that the demodulation would be back on AM. I have now set the frequencies from AM to FM in Chirp and now everything is fine again.
