### ISSUE TITLE
Issue with  screen

### ISSUE THREAD

**Issue by Romashca** [egzumer/uv-k5-firmware-custom#26]
![IMG_20231011_105944](https://github.com/egzumer/uv-k5-firmware-custom/assets/83151488/5c7ead89-7276-42ce-9521-26dbe6761b68)
![IMG_20231011_104101](https://github.com/egzumer/uv-k5-firmware-custom/assets/83151488/c9bd4969-40d8-4920-ab55-e1ad9a13997c)
![IMG_20231011_104119](https://github.com/egzumer/uv-k5-firmware-custom/assets/83151488/67fd0cf0-60ad-4c15-bccf-1695dffb0731)
there is a problem with TX Disable on closed frequency ranges, the label does not disappear until the channel is switched and the transmission starts at the allowed frequency, also with warning labels such as Busy maybe something with the label timeout, I can't figure out how to fix it

**Comment by egzumer** [comment]
I don't have such a problem. Does it work like that when the plug is disconnected? Where did you get the firmware?

**Comment by Romashca** [comment]
it works the same way with the plug disconnected, the firmware from your repo

**Comment by egzumer** [comment]
But did you build your own or did you use the release provided, which version?

**Comment by Romashca** [comment]
collected in vision studio code , today from repo

**Comment by lohtse** [comment]
am wondering which Frqs,  I di have similar issue if AM band is one of the two selected Frqs on screen. And if AM is being received or just finished it can be a second or tow before I can trans on my other frq..

**Comment by Romashca** [comment]
yes it is am

**Comment by lohtse** [comment]
> yes it is am

then thats the actually issue... I am pretty sure because the Radios chips do funky things to get AM it takes time to switch back for FM... I notice the same issue on Stock FW's  and all other custom ones too but is a little worse on customs possible due to the AM fixes employed...

**Comment by Romashca** [comment]
with other messages the same trouble

**Comment by lohtse** [comment]
Ple

> yes, it 's Am , it's the same at closed frequencies, the inscription does not go out

Please don't forget that devs are making these radios do things they are not designed for.

> with other messages the same trouble

what other messages?

**Comment by egzumer** [comment]
All you do is press the PTT and the message stays on permanently? Every time?

**Comment by Romashca** [comment]
with other messages , the same trouble , for example , busy on a busy channel ,yes every time

**Comment by egzumer** [comment]
Did you try with the release provided?
https://github.com/egzumer/uv-k5-firmware-custom/releases

**Comment by Romashca** [comment]
not yet

**Comment by egzumer** [comment]
When dual watch is in use, the last channel that was receiving becomes an active channel for tx for couple of second, no issue there.

The issue supposedly is that the massage stays permanently.

**Comment by lohtse** [comment]
> When dual watch is in use, the last channel that was receiving becomes an active channel for tx for couple of second, no issue there.
> 
> The issue supposedly is that the massage stays permanently.

he needs to provide videos  to be fair...

**Comment by lohtse** [comment]
> When dual watch is in use, the last channel that was receiving becomes an active channel for tx for couple of seconds, no issue there.
> 
> The issue supposedly is that the massage stays permanently.

I never really saw it as an issue.. I accepted the radios limitations new and old ;-)

**Comment by Romashca** [comment]
https://github.com/egzumer/uv-k5-firmware-custom/assets/83151488/4f6bf0be-d339-40c4-a7b5-44378ed13962

**Comment by lohtse** [comment]
> Untitled.video.-.Made.with.Clipchamp.1.mp4

so thats the same as what I posted above

**Comment by Romashca** [comment]
it is worth paying attention to the fact that the second channel is already receiving and this one is still blocked

**Comment by Romashca** [comment]
you press transfer after the inscription has disappeared, but I have reception on the second channel

**Comment by lohtse** [comment]
watch it properly... it is rx when I first press   then I do it after the RX has finished also

**Comment by Romashca** [comment]
is it really so difficult to see and understand this

**Comment by Romashca** [comment]
watch the video carefully and find the differences

**Comment by lohtse** [comment]
we will have to agree to disagrre as I see the exact same situation..


and egzumer has stated this which is correct

When dual watch is in use, the last channel that was receiving becomes an active channel for tx for couple of seconds, no issue there.

**Comment by egzumer** [comment]
The problem stated was that the message stays permanently, not that it appears on the other channel.

**Comment by Romashca** [comment]
from your words, does it mean that there is no problem that the message hangs until the radio restarts ?  because it can hang for a long time?

**Comment by Romashca** [comment]
finally at least someone understood

**Comment by lohtse** [comment]
> from your words, does it mean that there is no problem that the message hangs until the radio restarts ? because it can hang for a long time?

custom build or prebuild fw?

**Comment by lohtse** [comment]
> finally at least someone understood



I was trying to fully understand and even replicate you issue... I could NOT replicate it....  Thats isnot , not understanding it is trying to reproduce a fault someone has to confirm YOUR issue buddy.. I could not do that.

**Comment by lohtse** [comment]
> > finally at least someone understood
> 
> I was trying too fully understand and even replicate your issue... I could NOT replicate it.... Thats is not , not understanding it is trying to reproduce a fault someone has to confirm YOUR issue buddy.. I could not do that.

**Comment by Romashca** [comment]
everything is written above

**Comment by Romashca** [comment]
as a tester, I described the problem, provided a video, I don't care at all if you are indifferent to the problem

**Comment by lohtse** [comment]
> everything is written above

what frqs are bing used as one is hidden and the video does not show all the info..

You state everything is written above.  yet yesterday someone had an issue unlocking their radio.. theyb failed to explain that it only happened during FM radio use. as they just stated when using the radio.. I could not reproduce their issue UNTILL all the facts became apparent.

**Comment by lohtse** [comment]
> as a tester, I described the problem, provided a video, I don't care at all if you are indifferent to the problem

I am literally trying to reproduce your DAMN issue so that it can be confirmed and help the dev.

**Comment by Romashca** [comment]
10 mb of video doesn 't give the full picture ? make it so that I can provide the video as a whole

**Comment by lohtse** [comment]
> 10 mb of video doesn 't give the full picture ? make it so that I can provide the video as a whole

try recording it fully and using this site to compress it as thats what I do

https://www.freeconvert.com/video-compressor/download

**Comment by lohtse** [comment]
and provide the FRQ ranges thats always hidden in the vids.   as well as confirm  fw version or if you compiled and setup used incase there is an actual setting conflict. even zip the fw.bin file and upload so the dev can take a look

**Comment by Romashca** [comment]
[firmware.zip](https://github.com/egzumer/uv-k5-firmware-custom/files/12868706/firmware.zip)

**Comment by lohtse** [comment]
> [firmware.zip](https://github.com/egzumer/uv-k5-firmware-custom/files/12868706/firmware.zip)

prebuild? custom built? which version? setup info??   I have been using and compiling egzumer for around two weeks and not had the issue... So the more info you provide the better it is for egzumer to help... in the mean time go to firmware channel and try the custom builds there and see if the issue continues and provide a vide etc

**Comment by Romashca** [comment]
air frequencies, low band, you don't know which frequencies are closed in the repo?

**Comment by lohtse** [comment]
> air frequencies, low band, you don 't know which frequencies are closed in the repo , how about busy lock ? what about high voltage? these messages hang until you restart the fucking radio

I am done with you... Am trying to help but you are not getting what you want do being abusive..  Godd luck and hope your radio dies

**Comment by Romashca** [comment]
downloaded the repository https://github.com/egzumer/uv-k5-firmware-custom ,compiled in visual studio code

**Comment by Romashca** [comment]
долбоёб конченный

**Comment by Romashca** [comment]
я надеюсь что ты сдохнешь от рака мозга!

**Comment by egzumer** [comment]
Try the relese i provided

**Comment by lohtse** [comment]
I assume this я надеюсь что ты сдохнешь от рака мозга! пидор! will be deleted given that this is what he said I hope you die of brain cancer! fag!

**Comment by Romashca** [comment]
relese is good. all work.

**Comment by egzumer** [comment]
Then provide what you change

**Comment by Romashca** [comment]
the release works, but I'm not used to asking and would like to change some data myself, font, etc.

**Comment by Romashca** [comment]
> Затем укажите, что вы изменяете

where should I specify this ?

**Comment by Romashca** [comment]
> Я предполагаю это, я надеюсь, что ты сдохнешь от рака мозга! ! будет удалено, учитывая, что это то, что он сказал, я надеюсь, что вы умрете от рака мозга! пидор!
it was addressed to you
https://github.com/lohtse

**Comment by egzumer** [comment]
If the only thing you change is makefile then provide the build option that you choose. You should have started with that. Think again, how am I suppose to track it down without it?

 If you made source code changes then you caused the bug that you have hunt down on your own.

**Comment by lohtse** [comment]
> If the only thing you change is makefile then provide the build option that you choose. You should have started with that. Think again, how am I suppose to track it down without it?
> 
> If you made source code changes then you caused the bug that you have hunt down on your own.

Literally what I was trying to get too... hence asking for build , if user compiled, setup used etc.

**Comment by Romashca** [comment]
I change the makefile from your repo , I don 't touch the source code , the output is what I wrote about

**Comment by Romashca** [comment]
> > Если единственное, что вы изменяете, это makefile, укажите выбранный вами вариант сборки. С этого надо было начать. Подумайте еще раз, как я могу отыскать его без него?
> > Если вы внесли изменения в исходный код, значит, вы вызвали ошибку, которую вам пришлось искать самостоятельно.
> 
> Буквально то, что я тоже пытался получить... Следовательно, запрашивается сборка, если пользователь скомпилирован, настройка используется и т. Д.

Go love yourself, I'm communicating with a person

**Comment by lohtse** [comment]
> I change the makefile from your repo , I don 't touch the source code , the output is what I wrote about

but if you provide the setup used it can help identify if it was a setting  that was enable or even disable that caused your issue!  Thats why I asked you for that info.

**Comment by lohtse** [comment]
> > > Если единственное, что вы изменяете, это makefile, укажите выбранный вами вариант сборки. С этого надо было начать. Подумайте еще раз, как я могу отыскать его без него?
> > > Если вы внесли изменения в исходный код, значит, вы вызвали ошибку, которую вам пришлось искать самостоятельно.
> > 
> > 
> > Буквально то, что я тоже пытался получить... Следовательно, запрашивается сборка, если пользователь скомпилирован, настройка используется и т. Д.
> 
> Go love yourself, I'm communicating with a person

There is no need for that at all...

**Comment by lohtse** [comment]
> #define ONE_OF_ELEVEN_VER
> 
> #ifdef GIT_HASH #define VER GIT_HASH #else #define VER "231004" #endif
> 
> #ifndef ONE_OF_ELEVEN_VER const char Version[] = "OEFW-"VER; const char UART_Version[] = "UV-K5 Firmware, Open Edition, OEFW-"VER"\r\n"; #else const char Version[] = "1o11+fagci-"VER; const char UART_Version[] = "UV-K5 Firmware, Open Edition, 1o11+fagci-"VER"\r\n"; #endif

the info fro the make file  not version file, version file will not actually give  version it defines how to write it on boot screen!

**Comment by Romashca** [comment]
# compile options (see README.md for descriptions)
# 0 = disable
# 1 = enable
#
ENABLE_CLANG                  := 0
ENABLE_SWD                    := 0
ENABLE_OVERLAY                := 0
ENABLE_LTO                    := 1
ENABLE_UART                   := 1
ENABLE_AIRCOPY                := 1
ENABLE_FMRADIO                := 0
ENABLE_NOAA                   := 0
ENABLE_VOICE                  := 0
ENABLE_VOX                    := 0
ENABLE_ALARM                  := 0
ENABLE_TX1750                 := 1
ENABLE_PWRON_PASSWORD         := 0
ENABLE_BIG_FREQ               := 0
ENABLE_SMALL_BOLD             := 0
ENABLE_KEEP_MEM_NAME          := 1
ENABLE_WIDE_RX                := 1
ENABLE_TX_WHEN_AM             := 0
ENABLE_F_CAL_MENU             := 1
ENABLE_CTCSS_TAIL_PHASE_SHIFT := 1
ENABLE_BOOT_BEEPS             := 0
ENABLE_SHOW_CHARGE_LEVEL      := 1
ENABLE_REVERSE_BAT_SYMBOL     := 1
ENABLE_CODE_SCAN_TIMEOUT      := 0
ENABLE_AM_FIX                 := 1
ENABLE_AM_FIX_SHOW_DATA       := 0
ENABLE_SQUELCH_MORE_SENSITIVE := 1
ENABLE_FASTER_CHANNEL_SCAN    := 1
ENABLE_RSSI_BAR               := 1
ENABLE_AUDIO_BAR              := 0
ENABLE_COPY_CHAN_TO_VFO       := 1
ENABLE_SPECTRUM               := 1
#ENABLE_SINGLE_VFO_CHAN        := 1
#ENABLE_BAND_SCOPE             := 1

#############################################################

**Comment by Romashca** [comment]
[Makefile.zip](https://github.com/egzumer/uv-k5-firmware-custom/files/12869321/Makefile.zip)
[firmware.zip](https://github.com/egzumer/uv-k5-firmware-custom/files/12869322/firmware.zip)

**Comment by Romashca** [comment]
[firmware.zip](https://github.com/egzumer/uv-k5-firmware-custom/files/12869326/firmware.zip)

**Comment by lohtse** [comment]
> # compile options (see README.md for descriptions)
> # 0 = disable
> # 1 = enable
> ENABLE_CLANG := 0 ENABLE_SWD := 0 ENABLE_OVERLAY := 0 ENABLE_LTO := 1 ENABLE_UART := 1 ENABLE_AIRCOPY := 1 ENABLE_FMRADIO := 0 ENABLE_NOAA := 0 ENABLE_VOICE := 0 ENABLE_VOX := 0 ENABLE_ALARM := 0 ENABLE_TX1750 := 1 ENABLE_PWRON_PASSWORD := 0 ENABLE_BIG_FREQ := 0 ENABLE_SMALL_BOLD := 0 ENABLE_KEEP_MEM_NAME := 1 ENABLE_WIDE_RX := 1 ENABLE_TX_WHEN_AM := 0 ENABLE_F_CAL_MENU := 1 ENABLE_CTCSS_TAIL_PHASE_SHIFT := 1 ENABLE_BOOT_BEEPS := 0 ENABLE_SHOW_CHARGE_LEVEL := 1 ENABLE_REVERSE_BAT_SYMBOL := 1 ENABLE_CODE_SCAN_TIMEOUT := 0 ENABLE_AM_FIX := 1 ENABLE_AM_FIX_SHOW_DATA := 0 ENABLE_SQUELCH_MORE_SENSITIVE := 1 ENABLE_FASTER_CHANNEL_SCAN := 1 ENABLE_RSSI_BAR := 1 ENABLE_AUDIO_BAR := 0 ENABLE_COPY_CHAN_TO_VFO := 1 ENABLE_SPECTRUM := 1 #ENABLE_SINGLE_VFO_CHAN := 1 #ENABLE_BAND_SCOPE := 1
> 
> #############################################################



this I what I have 

![image](https://github.com/egzumer/uv-k5-firmware-custom/assets/48331155/59ad7564-4eb4-4e58-bf37-8515e2498320)

**Comment by Romashca** [comment]
[firmware.zip](https://github.com/egzumer/uv-k5-firmware-custom/files/12869351/firmware.zip)

**Comment by lohtse** [comment]
> [firmware.zip](https://github.com/egzumer/uv-k5-firmware-custom/files/12869351/firmware.zip)

Now flashed your compiled version... what are the actual Frqs used so I can try and reporduce

**Comment by egzumer** [comment]
That is all I need for now, I'm away, I'll look at it when I'm back.

@lohtse you are too agressive in our posts, stop doing that. And to both of you, plowing through your shit posting is the last thing I want to do. Short questions, short answers, facts. Want to have discussion go somewhete else.

**Comment by Romashca** [comment]
130,300 , 118,200 , 27,135

**Comment by lohtse** [comment]
> 130,300 , 118,200 , 27,135 please try this

with you make file it just happened with out the need to use yours . both frqs was Airband. and  pushing ppt caused it

**Comment by lohtse** [comment]
Once I enabled

ENABLE_TX_WHEN_AM             := 1


the issue is resolved for me

thats the only thing I changed in tyour make file..

tx disabled is dispalyed  waited a secind press ptt  message diappears and can trasmit

**Comment by lohtse** [comment]
reflashed  my prefered FW  checked functions,  reset the provide make file  to ENABLE_TX_WHEN_AM             := 0  reflashed and back to the issue reported,   reset manke back you ENABLE_TX_WHEN_AM             := 1   reflashed and problems resolved

**Comment by Romashca** [comment]
try to turn on channel busy lock now, transmit fm and any frequency from 144 to 435 mhz on a busy channel. you will be surprised

**Comment by lohtse** [comment]
> try to turn on channel busy lock now, transmit fm and any frequency from 144 to 435 mhz on a busy channel. you will be surprised

with the channels I have set I have no busy  message   on ranges 15X.XXXXX and 40X.XXXX   but do get tx disabled after an AM and wish to trans on 25X.000 range  only fix is a reboot

**Comment by Romashca** [comment]
without a difference

**Comment by lohtse** [comment]
> without a difference
if I don't  do this ENABLE_TX_WHEN_AM             := 1   I know I will have issues... As it happened instantly when I tried as stated

**Comment by Romashca** [comment]
"if I'm not looking, then there's no problem "

**Comment by Romashca** [comment]
is there a problem ? or not?

**Comment by egzumer** [comment]
This is because of the FM radio disabled, it blocks some code that resets the VFO state. 
BTW linux compiler (I use [docker](https://github.com/egzumer/uv-k5-firmware-custom#building) ) creates smaller binaries that can fit FM radio too.
Your option + FM radio: [firmware.packed.zip](https://github.com/egzumer/uv-k5-firmware-custom/files/12874891/firmware.packed.zip)

**Comment by Romashca** [comment]
ERROR: failed to solve: process "/bin/sh -c git submodule update --init --recursive" did not complete successfully: exit code: 128
docker: Error response from daemon: user declined directory sharing C:\uv-k5-egzumer-firmware-custom-main\compiled-firmware.
