### ISSUE TITLE
 Error in compiling the firmware

### ISSUE THREAD

**Issue by JollyH0789** [egzumer/uv-k5-firmware-custom#264]
Hi there is an error in compiling the firmware, I downloaded the package without activating anything
![Immagine 2023-12-14 100138](https://github.com/egzumer/uv-k5-firmware-custom/assets/150172740/77d6fe40-7980-4c4e-90b5-fc4919735f70)

**Comment by egzumer** [comment]
Fixed, I use different version of compiler and I don't get those, this is why it went through.
FYI this may be used as an alternative https://github.com/egzumer/uv-k5-firmware-custom?tab=readme-ov-file#github-codespace-build-method
