### ISSUE TITLE
battery indication not working in codespace build

### ISSUE THREAD

**Issue by gartnl** [egzumer/uv-k5-firmware-custom#269]
When I compile the firmware on github codespace the battery indicator does not work but shows all bars at every percentage.
This happens even with a brandnew codespace and unaltered code. But in the SA the battery indication is ok again.
In the prebuild v0.20.1 it does work too. That's the same sourcecode I believe?

**Comment by egzumer** [comment]
Latest code refactoring introduced a bug. Nothing to do with a build method.

**Comment by gartnl** [comment]
tnx. You are faster than the speed of light :)
