### ISSUE TITLE
Inconsistent Smeter indications

### ISSUE THREAD

**Issue by Skelm01** [egzumer/uv-k5-firmware-custom#27]
Hi, great work first of all. 
A little issue, the Smeter indication is inconsistent. When, for example, the numerical indication shows 9+10 the graphic bar is approximately halfway and should correspond at most to a signal of 6/7

**Comment by zhaoparrot** [comment]
I think in this code, full scale is not S9.  it's S9+30.

**Comment by egzumer** [comment]
The max is indeed S9+30. Other than that I have little knowledge how it should work.
Also I imported RSSI calibration fix released by @DualTachyon
