### ISSUE TITLE
uvk5-chirp-driver (COMPILER_STATUS_LIST = ["DISABLE", "ENABLE"])

### ISSUE THREAD

**Issue by schinfo** [egzumer/uv-k5-firmware-custom#271]
It's "DISABLE", not "DESABLE"

**Comment by schinfo** [comment]
Another bug:

"FUNCTION" - not "FONCTION"

**Comment by schinfo** [comment]
[https://github.com/egzumer/uvk5-chirp-driver/blob/main/uvk5_EGZUMER.py](url)

**Comment by ErikS-web** [comment]
Found it...

https://github.com/egzumer/uvk5-chirp-driver/blob/main/uvk5_EGZUMER.py

"DESABLE" at line 287

"FUNCTION" - not "FONCTION" and line 2157 and more ( 12 times)

**Comment by ErikS-web** [comment]
O, thanks for signalling

**Comment by egzumer** [comment]
Thank you, but this is wrong repo.
As I said this is a very crude version, not really usable yet.
I'm not even the one who is working on it, let the guy comeup with a somewhat working version, then I'll open issues section there. Until then I don't take any issues regarding that project.
