### ISSUE TITLE
Backlight reverts to full brightness 

### ISSUE THREAD

**Issue by kittenarmy** [egzumer/uv-k5-firmware-custom#275]
v0.20.1

Steps to reproduce:
Set BLMax to 5 (BLMin stay set 0), press M to confirm - backlight reverts to full brightness until press exit.
Press M and backlight is full brightness again.

Also triggered by:
Press M to open menu, scroll with up/down to BackLt - backlight reverts to full brightness until press exit.

**Comment by JuantAldea** [comment]
I think it always lights at full brightness when pressing the M key, isn't in?

**Comment by egzumer** [comment]
This is inherited from 1o11 and I left it. The idea is I guess to allow bringing back the backligth settings in a dark when it was set to off.

**Comment by JuantAldea** [comment]
I have proposed solution of the "side effects" of this, although it is really cosmetic and it increases the binary size so I have mixed feelings about it.

**Comment by gartnl** [comment]
I actually like the backlight at FULL when entering or traversing the menu, it's kind of a failsafe. Just imagine you are by accident setting MAX to 1 ( might happen if you think you are setting MIN ). Press exit twice or simply wait for the timeout of the backlight.
Setting it to MAX when leaving the menu is fine, but keep it on FULL as long as you are in MENU.

**Comment by JuantAldea** [comment]
Yes, the failsafe is out of discussion. But it is also true that it is not returned to the configured max BL exactly when it should.

If you go above the Blit options, you will see that the BLit does not return to the configured until you are "two options away" from them, or actually, two key-presses away.

**Comment by egzumer** [comment]
The button pressing functions are a mess, I know it is not perfect. I didn't want to spend more time fighting that, this was the best I could get it to be then.
I'll take a look at the solution later.

**Comment by egzumer** [comment]
It is cosmetic and takes some memory space, but the operation is nicer, I like it. I tried to make it work like that before.

**Comment by kittenarmy** [comment]
> I actually like the backlight at FULL when entering or traversing the menu, it's kind of a failsafe. Just imagine you are by accident setting MAX to 1 ( might happen if you think you are setting MIN ). Press exit twice or simply wait for the timeout of the backlight. Setting it to MAX when leaving the menu is fine, but keep it on FULL as long as you are in MENU.

If you have dark adapted eyes, using the radio with this behaviour is actually painful and not at all intuitive. It somewhat defeats the point of having option to lower the brightness. I prefer set and forget and expect the same. I suggest it be a build option like the guarding of TX on all frequencies.

**Comment by egzumer** [comment]
I'm raising the stakes: 1151cf86670d5c9076f0e947ab1f73b946fabb66

Interestingly, there is more code but it takes 52B less space :)

**Comment by kittenarmy** [comment]
> I'm raising the stakes: [1151cf8](https://github.com/egzumer/uv-k5-firmware-custom/commit/1151cf86670d5c9076f0e947ab1f73b946fabb66)
> 
> Interestingly, there is more code but it takes 52B less space :)

This is great. Thank you!
