### ISSUE TITLE
Build broken on Mac OS

### ISSUE THREAD

**Issue by alexbirkett** [egzumer/uv-k5-firmware-custom#284]
Commit f074114d1343a5955ac7dab2d01aa66505800132 broke the build on Mac OS

```
uv-k5-firmware-custom % make 
GIT_HASH = f074114
Python 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 

```

**Comment by alexbirkett** [comment]
This let me build. I'm not sure how to fix it properly.

[macbuildfix.patch](https://github.com/egzumer/uv-k5-firmware-custom/files/13689107/macbuildfix.patch)

**Comment by egzumer** [comment]
try now

**Comment by alexbirkett** [comment]
It works! Thanks
