### ISSUE TITLE
Annoying tuning in VFO mode

### ISSUE THREAD

**Issue by zylka5** [egzumer/uv-k5-firmware-custom#286]
Irytujące strojenie w trybie VFO

W poszukiwaniu słabych stacji przy włączonym monitorze używamy strzałek góra/dół aby przestroić o dany krok częstotliwość. Gdy używamy krótkich wciśnięć jest w porządku, ale gdy **przytrzymamy dłużej klawisz** częstotliwość na wyświetlaczu zamienia się ale w odsłuchu pozostaje ta to była w momencie wciśnięcia, Więc jeżeli podczas takiego strojenia natrafimy na jakiś odbiór nie usłyszymy go i zostanie przegapiona. Przydało by się by to co monitorujemy było aktualizowane na bieżąco. Aby zaktualizować trzeba puścić klawisz tylko w tedy dodatkowo następuje cisza i trzeba dodatkowo wcisnąć klawisz którejś strzałki. A to spowoduje przestrojenie dodatkowo o jeden krok i trzeba wciąć przeciwną żeby wrócić na poprzednią częstotliwość. Czyli kumulacja dwu błędów. Proszę o poprawienie bo to bardzo irytuje podczas szukania słabych stacji. W alternatywnych zmodyfikowanych softach nie ma takiego efektu.

Translate:
When searching for weak stations with the monitor on, we use the up/down arrows to tune the frequency by a given step. When we use short presses it's fine, but when we hold the key down longer the frequency on the display changes but the audio stays on what it was at the moment of pressing, So if during such tuning we come across some reception we won't hear it and it will be missed. It would be good if what we monitor is updated live. To update, you need to release the key only then additionally there is silence and you need to additionally press the key of one of the arrows. And this will tune an additional step and you need to press the opposite one to get back to the previous frequency. So an accumulation of two errors. Please fix this because it's very irritating when searching for weak stations. In alternative modified softwares there is no such effect.

**Comment by ErikS-web** [comment]
Is this the same as #228 ?

**Comment by zylka5** [comment]
No.

sob., 16 gru 2023 o 14:21 ErikS-web ***@***.***> napisał(a):
