### ISSUE TITLE
Function explanation 

### ISSUE THREAD

**Issue by Frie1960** [egzumer/uv-k5-firmware-custom#29]
So far I am very satisfied with the latest adjustments of the v.10 release, but when I looked around the menu I came across unknown functions:

Menu 48: LIVE
Menu 43: RSP
Menu 33: COMPND
Menu 14: BUSYCL

Maybe someone among you can giving me the latest function explanation

Thank you very much for all the effort, 73 and all the best
Best regards, Frie Van Peer

**Comment by curselink** [comment]
> So far I am very satisfied with the latest adjustments of the v.10 release, but when I looked around the menu I came across unknown functions:
> 
> Menu 48: LIVE Menu 43: RSP Menu 33: COMPND Menu 14: BUSYCL
> 
> Maybe someone among you can giving me the latest function explanation
> 
> Thank you very much for all the effort, 73 and all the best Best regards, Frie Van Peer

Menu 48: D LIVE - live dtmf decoder on screen
Menu 43: D RSP - same as stock, with string alterations
"DTMF Decoding Response (NULL/DO NOTHING: Close, RING: Local ringing, REPLY: reply response, BOTH: local ringing +reply response)"
Menu 33: COMPND - compander function
Menu 14: BUSYCL - same as stock BCL - busy channel lock

**Comment by Frie1960** [comment]
Great how you take the time and effort to respond to my questions 🙏🙏🙏 Thank you so much ⭐⭐⭐⭐⭐ I stay with respect, Frie van Peer

**Comment by ErikS-web** [comment]
**The PTT on external** microphone acts different than the **internal PTT (side-)button**. 
On external PTT the TX waits until no RX-signal is received. So this is handy if you want to react a.s.a.p. in a conversation ;-)

**Comment by ErikS-web** [comment]
This nice instruction for the Spectrum Analyzer

[QuanSheng UV K5. Spectrum analyzer guide EN.pdf](https://github.com/egzumer/uv-k5-firmware-custom/files/13125693/QuanSheng.UV.K5.Spectrum.analyzer.guide.EN.pdf)
and

[QuanSheng UV K5. Guía analizador de espectro ( ES ).pdf](https://github.com/egzumer/uv-k5-firmware-custom/files/13125699/QuanSheng.UV.K5.Guia.analizador.de.espectro.ES.pdf)

**Comment by ErikS-web** [comment]
More text-description on **Main menu** items can be found here: https://github.com/ludwich66/Quansheng_UV-K5_Wiki/wiki/Manual_EN

**Comment by egzumer** [comment]
> **The PTT on external** microphone acts different than the **internal PTT (side-)button**.
> On external PTT the TX waits until no RX-signal is received.

This seems to be a hardware issue as I wasn't able to find separate function for separate PTT source. Looks like voltage levels are simply shifted when speaker gets activated and it doesn't trigger the PTT.

**Comment by ErikS-web** [comment]
The above comments have been incorporated into the wiki today.

**Comment by egzumer** [comment]
Thanks
