### ISSUE TITLE
Some Menu settings are not stored permanently

### ISSUE THREAD

**Issue by valki2** [egzumer/uv-k5-firmware-custom#300]
for example PTT ID or scramble settings wont survive a power off-on cycle"
Using versinon 0.21 on a uv-k5 and a uv-k6

**Comment by Arikshten** [comment]
You have to save certain settings (like the two you mention) within the/a channel memory for them to persist. 
Specifically for such settings which are for a particular channel only. 

So to get this to persist :
- Go to the channel you wish to enable Scramble for 
- Enable Scramble in the menu
- then save the chanel in the memory with this update. 
- currently option 16 in the menu to save 

Once done if you power off and back on that setting should persist. 

I believe this is the intended functionality. 

Hope that helps
