### ISSUE TITLE
Am is not correctly stored / decoded

### ISSUE THREAD

**Issue by valki2** [egzumer/uv-k5-firmware-custom#301]
when saving eg. AM 126.025000  (via chirp, using the unlimited module), then the frequency is not in AM mode but in FM mode. via scanner i can change to am and voila works.

for testing: leaving everything and just flashing fagcis firmware -> that works with the stored AM frequency out of the box (even without transferring cia chrip again)

**Comment by egzumer** [comment]
Use dedicated chirp driver https://github.com/egzumer/uvk5-chirp-driver
