### ISSUE TITLE
STE

### ISSUE THREAD

**Issue by karacsonyisandor** [egzumer/uv-k5-firmware-custom#31]
The squelch tail elimination is not working.

**Comment by egzumer** [comment]
This is caused by ENABLE_CTCSS_TAIL_PHASE_SHIFT, something introduced by @OneOfEleven, but the detector seems to be misconfigured for that to work. This FW has it disabled:
[firmware.packed.zip](https://github.com/egzumer/uv-k5-firmware-custom/files/12967897/firmware.packed.zip)
