### ISSUE TITLE
Channels not removed/skipped from the list scan

### ISSUE THREAD

**Issue by JohnRobson** [egzumer/uv-k5-firmware-custom#327]
Using the "PSCPS.exe" I can add channels to the scan list (1 or 2), but I can't remove them, just manually.

**Comment by ErikS-web** [comment]
Here **Chirp** is recommended, not PSCP.

Best is use it with[ EGZUMER-driver,](https://github.com/egzumer/uvk5-chirp-driver) that is specific for that firmware.

**Comment by ErikS-web** [comment]
And read this section in the Wiki also: [Radio Operation ](https://github.com/egzumer/uv-k5-firmware-custom/wiki/Radio-operation)
