### ISSUE TITLE
Dtmf compile issue

### ISSUE THREAD

**Issue by lohtse** [egzumer/uv-k5-firmware-custom#328]
as of  d75209b   disabling DTMF  files to compile and gives the folowing
![image](https://github.com/egzumer/uv-k5-firmware-custom/assets/48331155/4caf128b-3d45-4e58-b946-3ccff40febcc)

the settings arre the same as your make fike other than disabled DTMF
![image](https://github.com/egzumer/uv-k5-firmware-custom/assets/48331155/8444e0fe-c24a-4a33-8417-83dbecc8a500)

**Comment by JuantAldea** [comment]
This one is on me
