### ISSUE TITLE
AIRBAND AM Problem in V.012 

### ISSUE THREAD

**Issue by hssbo** [egzumer/uv-k5-firmware-custom#34]
Hello EGZUMER! Congratulations on your work, I really appreciate your firmwares. In v0.12 I noticed a loss of sensitivity in AM airband reception. I live near an airport and after this update reception decreased a lot. I hope I'm helping with my feedback! TKS

PS.: The functions added to the menu were very good, especially the reorganization and programming of the side keys!

**Comment by hssbo** [comment]
Yes, I downgraded to v0.11...

**Comment by egzumer** [comment]
Did you try back and forth and it is always better on 11 and much worse on 12? As I said nothing was changed whatsoever that could cause that. Also I don't notice any degradation in AM reception.

**Comment by hssbo** [comment]
Yes, is always better on 11...
Reception is more sensitive in version 11... the number of listens is greater...
Version 12 seems "deaf" to airband...

**Comment by JMSCompSci** [comment]
Did you enable the "AM Fix" option in settings?  It boosted the audio big time for me.

**Comment by egzumer** [comment]
I've set up two radios, one with v11 and second with v12 and run them together. There is no difference. Both at the same time on sql 4 receive even as low signals that are noisy and hard to understand.
I also asked on my local chat, nobody confirmed this problems.

**Comment by hssbo** [comment]
Anyway, maybe it was a false impression I had. Thank you very much for your attention!

**Comment by hssbo** [comment]
> Did you enable the "AM Fix" option in settings? It boosted the audio big time for me.

Yes
