### ISSUE TITLE
Use of uvk5_EGZUMER.py prevents option to turn Duplex "OFF"

### ISSUE THREAD

**Issue by Big-Mal99** [egzumer/uv-k5-firmware-custom#341]
The option to turn Duplex "OFF" is no longer available and can not be copied from .csv file

**Comment by ErikS-web** [comment]
Look like an issue for the Chirp-driver

In that case...

Please place this Issue [here](https://github.com/egzumer/uvk5-chirp-driver/issues) at the Chirp driver and close this issue.
