### ISSUE TITLE
Minor display: battery level show 100%, full bar and power plug when programming cable is connected

### ISSUE THREAD

**Issue by joc2** [egzumer/uv-k5-firmware-custom#351]
This is just a minor thing that i found on the display while the programming cable is connected.

you turn on the radio ( without pressing any boutton, or by pressing the bouton for the extra menu ) 
the radio battery show 60% let say for this example....

you plug the programming cable in the radio and then in the computer, ( to program with chirp some option )
The level of the battery goes to full,100% and display the power plug on the display, but the battery is not charging at all. 
The led blue on top of the radio never goes on either.

if you let it connected with the programming cable for a while, thinking it's charging ( as display on radio show it) .
Then you disconnect de programming cable, the battery level gone a be less than the initial 60 %... depending how long you have let it connected. maybe...55% or less
 
this is just a wrong display, while the programming cable is connected and give false thinking of full battery and charging.

**Comment by egzumer** [comment]
This is a hardware bug, nothing to do with software
