### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by lohtse** [egzumer/uv-k5-firmware-custom#353]
Very odd issue  asof Build de608a9

TX stays stuck on I use and if I press keys I get button tones(differnt tone per key)  only way to do anything is to reflash to previous build.. NOTHING has changed in my make file and has been my preferred setup for 7-8 weeks.

**Comment by egzumer** [comment]
I meant radio configuration

**Comment by egzumer** [comment]
It is not the config that has changed it's the code. But without the config I can't reproduce the issue.
I rolled back recent changes, it should work ok now.
