### ISSUE TITLE
Spectrum freezes when switch to AM

### ISSUE THREAD

**Issue by Skelm01** [egzumer/uv-k5-firmware-custom#36]
Hello,
I inform you that Spectrum keep freezing while switching to AM. 
For example: VFO 135.450mhz - F5 - 0

**Comment by egzumer** [comment]
Every time? This was reported before #4 but I can't reproduce that, never happened to me.

**Comment by egzumer** [comment]
Use [k5prog_win.exe](https://github.com/OneOfEleven/k5prog-win/raw/main/k5prog_win.exe) to dump config and calibration, and share the binaries here. This has to be related to particular configuration I think. Maybe I'll be able to to trigger this on my radio with your settings. I don't have a clue otherwise.

**Comment by Skelm01** [comment]
> Use [k5prog_win.exe](https://github.com/OneOfEleven/k5prog-win/raw/main/k5prog_win.exe) to dump config and calibration, and share the binaries here. This has to be related to particular configuration I think. Maybe I'll be able to to trigger this on my radio with your settings. I don't have a clue otherwise.

Ok, I got the 2 config files, how I can I share here?

**Comment by Skelm01** [comment]
> Use [k5prog_win.exe](https://github.com/OneOfEleven/k5prog-win/raw/main/k5prog_win.exe) to dump config and calibration, and share the binaries here. This has to be related to particular configuration I think. Maybe I'll be able to to trigger this on my radio with your settings. I don't have a clue otherwise.

Bin files are not supported for sharing, how can I do?

**Comment by egzumer** [comment]
Zip them. Also write what steps are needed to reproduce. Turn on the radio, F+5 and wait?

**Comment by Skelm01** [comment]
> Zip them. Also write what steps are needed to reproduce. Turn on the radio, F+5 and wait?
VFO on Air band AM, F+5 wait 2-3 sec then press 0 to activate AM

[my_config.zip](https://github.com/egzumer/uv-k5-firmware-custom/files/13047140/my_config.zip)

**Comment by egzumer** [comment]
I didn't manage to reproduce the problem unfortunately.
