### ISSUE TITLE
Channel scanning problem

### ISSUE THREAD

**Issue by mfarikan** [egzumer/uv-k5-firmware-custom#366]
There is a problem in channel scanning. It scans only one scan list, not two scan lists. Menu 20 & 21 > Slist1 and Slist2 look the same.

**Comment by egzumer** [comment]
It seems to me that you didn't read the manual.

**Comment by mfarikan** [comment]
I read it, but I think you haven't checked the problem

**Comment by mfarikan** [comment]
![photo_2024-01-01_22-05-56](https://github.com/egzumer/uv-k5-firmware-custom/assets/150275184/e6da6461-0ba8-436a-921c-951bc114acf5)
![photo_2024-01-01_22-06-02](https://github.com/egzumer/uv-k5-firmware-custom/assets/150275184/c94c1174-166c-4372-90ac-ca93be7f619c)
![photo_2024-01-01_22-06-06](https://github.com/egzumer/uv-k5-firmware-custom/assets/150275184/17c48b43-0049-4db2-85c6-59db38fc9988)
![photo_2024-01-01_22-06-09](https://github.com/egzumer/uv-k5-firmware-custom/assets/150275184/9589669d-eac6-48ed-95db-b3704686a77a)

**Comment by egzumer** [comment]
Ok I see, sorry.

**Comment by mfarikan** [comment]
It's okay, the important thing is that you're interested. 73.
