### ISSUE TITLE
request: option to scan on when powered on

### ISSUE THREAD

**Issue by jflinchbaugh** [egzumer/uv-k5-firmware-custom#368]
I always like my radio to scan, so every time I turn it on, I need to remember to press the shortcut key I've assigned to enable scan.
If the firmware had an option to automatically scan when turned on, it would save me the press of the button.

(BTW, I love the combination of features available in this firmware. It's so much more intuitive and useful than stock. 👍 )

**Comment by egzumer** [comment]
Sorry I don't see a benefit in it, I'm not willing to work on that.

**Comment by jflinchbaugh** [comment]
Would you accept a PR for the feature of I were to give it a try?

**Comment by egzumer** [comment]
It consumes memory space, makes the menu crowded, and only saves one click, so as a default option no. But as a custom build option I see no problem.
