### ISSUE TITLE
Single Channel Mode

### ISSUE THREAD

**Issue by Big-Mal99** [egzumer/uv-k5-firmware-custom#372]
Include single channel mode as in IJV mod giving a much clearer screen

**Comment by ErikS-web** [comment]
Is this idea the same as #124 (and #111) ?

**Comment by Big-Mal99** [comment]
I don't think this is the same as #111 and #124.  I was after the ability
to only display 1 channel at a time similar to what is shown here
[image: image.png]

**Comment by ErikS-web** [comment]
No image ?!. Pse try again on the web-site.

**Comment by Big-Mal99** [comment]
Image that was attached

![IJV Firmware single mode screenshot](https://github.com/egzumer/uv-k5-firmware-custom/assets/147701549/db025adc-0698-4485-befa-4749ebeeedc3)

**Comment by egzumer** [comment]
Duplicate #124
