### ISSUE TITLE
Add activation of 1750 Hz in menu

### ISSUE THREAD

**Issue by ErikS-web** [egzumer/uv-k5-firmware-custom#38]
I am missing the 1750 hz, which I had programmed under long-press Second Function key.

Idea is to add an 1750 ON/OFF in (hidden) menu.

**Comment by egzumer** [comment]
I consider this function irrelevant, it is disabled by build options in my releases. You can still send 1750 tone by holding `PTT` + `SIDE BUTTON 2`

**Comment by ErikS-web** [comment]
Yes indeed. 

Thanks for answer,

Suggestion to place the info also on your Wiki. "You can send 1750 tone by holding PTT + SIDE BUTTON 2"

**Comment by egzumer** [comment]
https://github.com/egzumer/uv-k5-firmware-custom/wiki/Button-functions#function-button-ii

**Comment by ErikS-web** [comment]
This is 'perfect' !
