### ISSUE TITLE
Stopping Scan frequency range - description in Wiki not correct

### ISSUE THREAD

**Issue by ErikS-web** [egzumer/uv-k5-firmware-custom#381]
Text [scan-frequency-range-function](https://github.com/egzumer/uv-k5-firmware-custom/wiki/Radio-operation#scan-frequency-range-function) says...

**_Scan frequency range function_**

- switch to frequency mode
- set upper and lower VFO frequencies to scan range boundaries
- long-press `5 NOAA`, `ScnRng` label should show up
- start scan with long-press `* Scan`
- it will scan between given boundaries
- **long-press `5 NOAA` or `EXIT`, or switch VFOs to exit `ScnRng` mode**

Suggest to change last line. Should be edited to...

- long-press EXIT to _exit ScnRng mode_

and

- short-press `EXIT` or `PTT` _Halt scanning_ (to initial- or last received frequency)

than Continue scanning with `* Scan` or

- long-press `5` or long-press `EXIT`, or long-press `2 A/B` to _exit ScnRng mode_

**Comment by egzumer** [comment]
Do you have any problems using it? Lets not make it any better than it needs to be.
