### ISSUE TITLE
Scan List1 and List2 but not ALL channels

### ISSUE THREAD

**Issue by AubsUK** [egzumer/uv-k5-firmware-custom#385]
Running Release v0.21

When a channel is stored, it can be added into List1 or List 2 or no list.

When scanning channels, you have an option of 1 (List1), 2 (List2) or * (ALL channels).  This concurs with the [instructions](https://github.com/egzumer/uv-k5-firmware-custom/wiki/Radio-operation#memory-channels-scanning).

However, if I have a channel stored that I don't want to scan because it is constant static from my location (UHF repeater), but I want to have it in my channel list so I can hear it when I move locations, I can remove it from the List1, so when I scan List1 or List2, it is not scanned.  But if I scan *, it gets included (ALL channels).

**Question:** Is there a way to scan List1 (1) and List2 (2) but not ALL channels (*) ? - So it would have "1+2" or "12" in the top left.

**Comment by egzumer** [comment]
No there is not

**Comment by AubsUK** [comment]
Thanks for replying, appreciate it.

Is there any way to 'lock out' a channel ?

**Comment by egzumer** [comment]
No, all is described in the wiki, there are no hidden features.

**Comment by AubsUK** [comment]
Thanks, and sorry for asking.

Is this a limitation of the hardware itself, or could it be a feature through code? - Happy to look at the code to see if I can figure it out, unless you already know it's not possible.

**Comment by JuantAldea** [comment]
It's purely software

**Comment by egzumer** [comment]
`gEeprom.SCAN_LIST_DEFAULT` is what you should be looking for.

**Comment by AubsUK** [comment]
Thanks for picking this up @egzumer

It took me a little while to figure the code out, but I've raised a pull request https://github.com/egzumer/uv-k5-firmware-custom/pull/420 for the suggested change:
https://github.com/egzumer/uv-k5-firmware-custom/pull/420
