### ISSUE TITLE
sql calibration implementation suggested as on ijv firmware

### ISSUE THREAD

**Issue by pawol** [egzumer/uv-k5-firmware-custom#395]
please take into account an implementation of existing sql calibrations read from eeprom like in the original or ijv firmware. each band has sepatared sql calibration kept in the eeprom. for instance sql levels are shifted 14dBm between uhf and vhf bands . The issue can be easily investigated when ijv firmware is used, sql levels are shifted and eeprom is dumped. Of course sql calibration cannot be edited on original fw, ijv allows it.

**Comment by egzumer** [comment]
use chirp

**Comment by pawol** [comment]
it is not possible to recalibrate sql eeprom values by Chirp. Just battery and tx power

**Comment by pawol** [comment]
![Capture](https://github.com/egzumer/uv-k5-firmware-custom/assets/13277626/7146976f-3fcd-403a-a71c-d9073f01b937)

**Comment by egzumer** [comment]
You dont need chirp developer options
https://github.com/egzumer/uvk5-chirp-driver?tab=readme-ov-file#calibration-settings

**Comment by egzumer** [comment]
And I don't know where did you get that driver from, that is not my driver
