### ISSUE TITLE
tx power calibration implementation suggested as on ijv firmware

### ISSUE THREAD

**Issue by pawol** [egzumer/uv-k5-firmware-custom#396]
please take into account an implementation of tx power calibrations read from eeprom like in the original or ijv firmware. each band has sepatared tx calibration kept in the eeprom. for instance tx level can be different between uhf and vhf bands . The issue can be easily investigated when ijv firmware is used, Low, med, high levels are changed and eeprom is dumped. Of course calibration cannot be edited on original fw, ijv allows it.

**Comment by egzumer** [comment]
use chirp to change calibration values

**Comment by pawol** [comment]
you do not understood. Every L M H setting has own value in the eeprom. You can set eg. 0,5W for Low power on 2m band. You have to try ivj. Chirp has nothing common with this issue

**Comment by egzumer** [comment]
You don't understand, use calibration section in the chirp

**Comment by pawol** [comment]
Sadly I see here same regres like with 1of11

**Comment by egzumer** [comment]
What regres? Did check out the chirp driver or not? I guess not.

**Comment by egzumer** [comment]
Battery calibration is a different thing, it is one option and not gezilion different options like in the sql, or txp. Battery is easy. For TXP you need power meter and you need to know what youre doing, if someone whants to mess with that you have that option. I'm not adding that to the menu
