### ISSUE TITLE
Screen backlighting brightness 

### ISSUE THREAD

**Issue by KerseyPaul** [egzumer/uv-k5-firmware-custom#40]
Dear Egzumer;

As a feature request, would it possible to implement a menu option to adjust the LCD screen backlighting brightness..?

Thanks in advance!

P.s.: great job, IMO your firmware is the best so far!

**Comment by RoadRangerX** [comment]
I was told that the 1of11 firmware added this a couple weeks ago?

**Comment by egzumer** [comment]
Implemented on eda199d47a4c66be258a1ef5876d0235ce718518 and released
