### ISSUE TITLE
OneOfEleven's "F" symbol missing

### ISSUE THREAD

**Issue by LordVertice** [egzumer/uv-k5-firmware-custom#404]
As seen [here](https://github.com/OneOfEleven/uv-k5-firmware-custom#symbol-information), next to the compander's "C" (if on) there should be an "F" on the right side of the screen if the frequency is saved in a channel somewhere, but that doesn't appear to be the case. Is this an intentional omission from OneOfEleven's firmware, or a bug?

Not sure if this is related to #209 in any way, since the C symbol doesn't like showing up in some cases either.

**Comment by egzumer** [comment]
It is based on 1o11, but it is not 1o11. I don't know what the F is for, it was not implemented when I forked the project.
C missing is a bug, there is no place to put it in frequency mode because big font is used.
