### ISSUE TITLE
Will not tx using speaker mic PTT on a busy channel/active repeater

### ISSUE THREAD

**Issue by BLUESALOON** [egzumer/uv-k5-firmware-custom#41]
V11 release
I noticed that when an external mic is connected the radio **will not tx using mic PTT on a busy channel/active repeater.
BCL set to OFF.**
The PTT on the radio will tx the radio on a busy channel with external mic connected.
The PTT on external mic will tx radio on inactive channels.
I have tried multiple external mics, all with the same result.
Thank you very much for all your hard work
James MM6WER

**Comment by egzumer** [comment]
Does any firmware work any different in that exact situation? :)
I believe this is a hardware issue.

**Comment by BLUESALOON** [comment]
Thank you for your quick reply.
I wasn't aware that it was a known hardware issue.
Thanks again
