### ISSUE TITLE
noaa scan

### ISSUE THREAD

**Issue by eried** [egzumer/uv-k5-firmware-custom#417]
Hi, after enabling noaa on the makefile, I can see the `N1, N2...` list and I assume `NS` on top means noaa scanning, but the led does not blink as with the original firmware while scanning? just wondering if outside US there is never noaa transmissions or I am missing an step in the process :/

**Comment by egzumer** [comment]
You are on your own with noaa. There is no NOAA outside of the USA and I have no way to test it.

**Comment by eried** [comment]
Ok thanks :)
