### ISSUE TITLE
FM broadcast radio

### ISSUE THREAD

**Issue by lohtse** [egzumer/uv-k5-firmware-custom#428]
Just combiled a new version of the FW which now has the "FM radio band selection" but how we use and set the ranges we may wish too use???

**Comment by egzumer** [comment]
Yes and no. Those bands are what is offered by the Bk1080 chip. In theory it seems that you can set 108M frequency even if you choose the lowest range, but I won't attempt to play with this. If you want to know more study the BK1080 reference manual. What is important for me is that I can now scan proper range which in Europe is 87.5-108.
