### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by HotelMikeSierra** [egzumer/uv-k5-firmware-custom#432]
Sorry if this was answered elsewhere, new at this compiling thing.
Compiled the firmware with Docker, followed the instructions, but the firmware displayed is "EGZUMER 46e2d1" not v0.21.
Don't know if I’m doing something wrong.

Thank you.

![Screenshot 2024-01-21 163944](https://github.com/egzumer/uv-k5-firmware-custom/assets/151450245/f890ab32-2fdd-4d60-8514-c65463575857)
![02](https://github.com/egzumer/uv-k5-firmware-custom/assets/151450245/58aa3488-e037-4b4d-9ba1-ea2c99527aa4)

**Comment by Tyrbiter** [comment]
It's just a git hash value, it shows the latest commit used to build the release known as v0.21

**Comment by egzumer** [comment]
You will get the actual version only if you use my official release build, it is automatically set with github action. If you want to set it on your own you have to play with a VERSION_STRING in the makefile
