### ISSUE TITLE
Squelch Tail Elimination (STE).

### ISSUE THREAD

**Issue by slavikby** [egzumer/uv-k5-firmware-custom#434]
Hello. I noticed that the station transmits a Tail tone while transmitting. (An indirect sign of the transmission of this tone is that when the PTT is released, the station continues to transmit for several milliseconds). The STE menu item does not disable it. Is it possible to make it switchable? Thank you !!!

**Comment by OE1MWW** [comment]
[of](https://forums.radioreference.com/threads/squelch-tail-elimination-ste.341657/) 2016, but nothing has changed

**Comment by slavikby** [comment]
Thank you. That's exactly what it is. I'm wondering if it's possible to turn off this signal during transmission. When changing the STE menu item on the current firmware, the signal is retained.
