### ISSUE TITLE
Around 140.000 tx disabled after set band tx on

### ISSUE THREAD

**Issue by wkdake** [egzumer/uv-k5-firmware-custom#437]
Hi,

I set the band of 137-174MHz TX ON by all means that instructed on your wiki site (including choosing 'unlock all' 10 times), but it still could not tranmit in that freq range. It shows "tx disable". But it can transmit on 400-470MHz. I purchased this Quansheng K6 from China two days ago.

Thanks a lot!
Regard!

**Comment by wkdake** [comment]
i flashed back to the orginal Quansheng firmware, problem still. then i found that i set TX CTCS -8mhz, so i reset all, then in original firmware i finnally can tx on 137mhz. then i flashed agian egzumer firmware, and reset all again, chose unlock all 10 times again----Now my mind is in peace. thanks!

**Comment by wkdake** [comment]
So i guess, 130mHz tx is the hardware low limitation there, no matter how hacked on display, it won't work under that properly. am i right?

**Comment by egzumer** [comment]
You shouldn't transmit on 130MHz under any circumstances!!! This is airband (108-137)!

**Comment by wkdake** [comment]
> You shouldn't transmit on 130MHz under any circumstances!!! This is airband (108-137)!

Thanks for remindering, well noted. i tried transmission in my safe box door-semi-opened, hopefully did't bother anything above

**Comment by egzumer** [comment]
This radio is not AM capable and TX in AM mode is locked so nobody tries either way.
