### ISSUE TITLE
RF Gain behavior

### ISSUE THREAD

**Issue by tjcirillo** [egzumer/uv-k5-firmware-custom#440]
when i increase the RF gain and long press M, it reverts to zero.  then, when i try to raise it, it stays at zero and can only be lowered to negative numbers.  

is this a bug? or am i doing something incorrectly?

thank you, tom

**Comment by egzumer** [comment]
You must have mistaken firmwares here. I don't know what you talking about. There is only spectrum where gains can be adjusted but there is no longpress M there, and it doesn't behave like you said.

**Comment by tjcirillo** [comment]
i'm so sorry. you;re absolutely right. i have two radios, identical except one runs egz and the other ijv.   thanks so much

**Comment by tjcirillo** [comment]
this is my error
