### ISSUE TITLE
rssi/mic bar is hard to read

### ISSUE THREAD

**Issue by QuickXand** [egzumer/uv-k5-firmware-custom#45]
the rssi bar is too hard to reach the end. why not using the more common style like this?
![image](https://github.com/egzumer/uv-k5-firmware-custom/assets/96399652/f6e50ac9-5eb3-4688-b49c-a98f648bdb31)

**Comment by CaptainRi** [comment]
I have been hesitant to ask the same question. RSSI S bar can be optimized to look better, such as the style of zebra stripes, Or a style similar to YAESU FT-4XR.

**Comment by hssbo** [comment]
This RSSI bar is very beautiful...

**Comment by ErikS-web** [comment]
Is this what you prefer ? see here https://t.me/UVK5FW/1148
![Knipsel](https://github.com/egzumer/uv-k5-firmware-custom/assets/148579604/d09bc654-5f09-4696-80eb-c3e6ea8a25ef)

**Comment by hssbo** [comment]
> Is this what you prefer ? see here https://t.me/UVK5FW/1148 ![Knipsel](https://user-images.githubusercontent.com/148579604/278110445-d09bc654-5f09-4696-80eb-c3e6ea8a25ef.JPG)
> 
> Just testing and seems to work fine.

I installed it and it's working fine! I just disabled the rssi bar microphone so there wouldn't be different bars. TKS!

**Comment by egzumer** [comment]
Implemented on 38b1e5cbaa669f75f198da0f2cd1466408387706 and released

**Comment by QuickXand** [comment]
> Implemented on [38b1e5c](https://github.com/egzumer/uv-k5-firmware-custom/commit/38b1e5cbaa669f75f198da0f2cd1466408387706) and released
Thanks and very brillant job!
Is there any possible to make mic indicator looks same as the s-bar?

**Comment by CaptainRi** [comment]
> > Implemented on [38b1e5c](https://github.com/egzumer/uv-k5-firmware-custom/commit/38b1e5cbaa669f75f198da0f2cd1466408387706) and released
> > Thanks and very brillant job!
> > Is there any possible to make mic indicator looks same as the s-bar?

@egzumer
