### ISSUE TITLE
RxCTCS or RxDCS menù. the automatic scan does not start

### ISSUE THREAD

**Issue by quansheng1** [egzumer/uv-k5-firmware-custom#452]
Ciao. vai al menu 3.60 oppure 4.60 premi tasto (scan) la scansione automatica non si avvia. l'immagine rimane bloccata e non scorre.
HI. go to menu 3.60 or 4.60 press the (scan) button the automatic scan does not start. the image remains frozen and does not scroll.
I installed the latest firmware 0.22
Thank you

**Comment by MrHoerby** [comment]
It works for me, but you have to open the menu item first and then press scan.

**Comment by egzumer** [comment]
It won't scroll through all options. It uses the same mechanism as `4 FC` scan. When it says SCAN it is scanning.
