### ISSUE TITLE
Signal TX no clear

### ISSUE THREAD

**Issue by marmatBCN** [egzumer/uv-k5-firmware-custom#456]
I have been using Firmware Egzumer for a long time,
  However, there is a problem: when transmitting on the 2m and 70cm bands, a quiet parasitic tone can be heard in the background.
TX signal is not clear.
I downloaded the factory version and this problem does not exist, so it is clearly a matter of Exzumer firmware...

**Comment by mentanah** [comment]
Can't confirm that. Using scrambler?

**Comment by KvallVall** [comment]
Set backlight to 10 or off.

https://github.com/egzumer/uv-k5-firmware-custom/issues/405

**Comment by marmatBCN** [comment]
I don't know what scrambler you're asking about?

**Comment by marmatBCN** [comment]
Scrambler is off, backlight I tested

**Comment by marmatBCN** [comment]
I set BKLight on 10 now is ok...

**Comment by marmatBCN** [comment]
Yes thanks I set 10 now is okWysłane z MM iPhoneRegardsMarek SQ7BCNWiadomość napisana przez KvallVall ***@***.***> w dniu 03.02.2024, o godz. 20:31:﻿
Set backlight to 10 or off.
#405
