### ISSUE TITLE
Remove 7 shortcut-key VOX

### ISSUE THREAD

**Issue by ErikS-web** [egzumer/uv-k5-firmware-custom#47]
long press 7 is activating VOX
this happend to me bij accident

although for others keys it is very handy, why for this key ?
how can this be deactivated ?

**Comment by egzumer** [comment]
For all buttons long-press duplicates `F+` function. The only exception is button 5 which has it split between scanlist toggle and spectrum.

You can deactivate by your own modification to the source code in your own fork of this repository.
