### ISSUE TITLE
Add Spectrum Analyzer for M button Long press and set it with 27.60 menu

### ISSUE THREAD

**Issue by koffu** [egzumer/uv-k5-firmware-custom#479]
Hi!
Thank you for the amazing firmware for my K5!
Could you please add a shortcut to easily access spectrum analyzer on M button long press.

**Comment by radonslide** [comment]
The PullRequest #478 also includes this option to assign the function to the M button and side buttons. I added this to my sources yesterday and tested it positively. Hopefully this will be included in the official sources and in the next release.

**Comment by egzumer** [comment]
duplicate #359
