### ISSUE TITLE
It is not possible to transmit (Tx) if I have an external speaker/microphone connected and the transmitter is in the monitor.

### ISSUE THREAD

**Issue by tomas-cabaj** [egzumer/uv-k5-firmware-custom#481]
If I connect an external speaker and microphone, rx and tx work, but when I turn on the monitor on the radio, I can no longer transmit using the tx button on the microphone. (The tx button works on the radio). If I turn off the monitor on the radio, the button on the external microphone allows me to transmit (tx).

Thanks TMK :)

![tmk](https://github.com/egzumer/uv-k5-firmware-custom/assets/58072010/45824526-885e-4da8-aa44-3bd352e2ff71)

link:
https://www.aliexpress.com/item/1005005646328439.html?spm=a2g0o.productlist.main.23.1b6b2260tFlnVq&algo_pvid=08502416-37e7-4193-a2b1-8c2979cc8d3d&algo_exp_id=08502416-37e7-4193-a2b1-8c2979cc8d3d-11&pdp_npi=4%40dis%21CZK%21580.90%21290.45%21%21%2123.98%2111.99%21%402103868d17084227471938287e547c%2112000033871479403%21sea%21CZ%21800136260%21&curPageLogUid=mpy2TaLDIB6g&utparam-url=scene%3Asearch%7Cquery_from%3A

**Comment by f4axk** [comment]
xternal microphone connection
explanation here

https://github.com/egzumer/uv-k5-firmware-custom/discussions/267
