### ISSUE TITLE
BusyCL with externtal speaker/mic

### ISSUE THREAD

**Issue by ChrisLyonsIA** [egzumer/uv-k5-firmware-custom#487]
I'm currently running v0.22, and have found that while I can transmit using the HT PTT while receiving on the HT itself, I cannot do so when using the PTT on the speaker/mic, However, the PTT on the HT will still work when using the speaker/mic.  Is this a hardware or software issue?

**Comment by OE1MWW** [comment]
had been discussed in detail on [#267](https://github.com/egzumer/uv-k5-firmware-custom/discussions/267)
