### ISSUE TITLE
Cannot put eg. 470 MHz into VFO. Tried on the latest egzumer release

### ISSUE THREAD

**Issue by pawol** [egzumer/uv-k5-firmware-custom#5]
Cannot put eg. 470 MHz into VFO. Tried on the latest egzumer release.
The result is VF07 000.60252

**Comment by lohtse** [comment]
can confrm it happens


just needs to merge commits to resolve the issue as 1of11 has resolved it now...

**Comment by pawol** [comment]
repo refreshed
