### ISSUE TITLE
 #45 S-metro stile piotr022 

### ISSUE THREAD

**Issue by IT9-TOP** [egzumer/uv-k5-firmware-custom#51]
Hi, is it possible to insert this change on the latest version of the 1off11 firmware?

 #45 S-metro stile piotr022

**Comment by egzumer** [comment]
already released

**Comment by ErikS-web** [comment]
Yes, and works fine ;-)

**Comment by egzumer** [comment]
I didn't read carefully enough, is it possible to port this to newest 1o11? This isn't 1o11's repository so you have to ask there.
