### ISSUE TITLE
Feature Request: Add 3500mAh Battery capacity

### ISSUE THREAD

**Issue by karlfoley** [egzumer/uv-k5-firmware-custom#512]
USB C rechargeable batteries with an extended capacity of 3500mAh are now available. Would it be possible to add this new capactiy battery to the hidden battery menu so that a more accurate discharge curve is available for it, similar to the 2600mAh battery capacity please?

**Comment by AubsUK** [comment]
Plus buying the complete set, you get a spare dock **and**  a spare radio handset! Though yes, each to their own, some people don't want to have to carry a spare battery and would just prefer one slightly bigger to carry around.
