### ISSUE TITLE
Display frozen after voltage drops to 6.36V

### ISSUE THREAD

**Issue by romgeo2000** [egzumer/uv-k5-firmware-custom#513]
I’m using egzumer v0.22, on a Quansheng UV-K5(8), made in January 2024. 
No other firmware, except factory and egzumer v0.20, was previously loaded.

Steps:  
-	display: MR channel on A, MR scan on B
-	backlight settings: BackLt = 1 min, BLMin = 4, BLMax = 9
-	radio already open for a few hours before incident

**Actual result**: after battery voltage drops to 6.36V, the display freezes, backlight remains on, radio still draws current from battery that continues to discharge. 
I started to measure the battery, but when it reached **5.60V** (~5 min) I decided to shut the radio off, by power button. 

**Expected result**: after battery voltage drops to 6.36V, the radio should shut-off, to protect the battery.

**Comment by egzumer** [comment]
Battery is protected by an internal BMS circuit. It will cut off the voltage when it drops below certain point. This is how majority of li-ion powered devices work.
The freezing of the radio is a hardware design issue. There is nothing that can be done about that, that would make any sense.
