### ISSUE TITLE
I wanna Listen to LSB (Lower Side Band)

### ISSUE THREAD

**Issue by GhosTmodE2120** [egzumer/uv-k5-firmware-custom#545]
Just wanna say great mod is best one so far only things for me i ask why no LSB i see USB but no LSB i use this radio for listening only mostly for CB and HAM and everything i would be listening to would be CB AM,LSB/ HAM AM,FM,USB,LSB if its a memory issue theres a few things i dont need so they can be taken out so i can have LSB mode

**Comment by HakanKoseoglu** [comment]
As I understand, the actual mode is DSB, so it's both USB and LSB at the same time. Have you tried approaching the signals from the other side?

**Comment by GhosTmodE2120** [comment]
ive seen other mods do LSB and USB

**Comment by GhosTmodE2120** [comment]
27.385 Mhz LSB has alot of traffic throughout the day and i wanna listen with out having to use another radio
