### ISSUE TITLE
"Release all keys" after flashing firmware

### ISSUE THREAD

**Issue by hiddenvs** [egzumer/uv-k5-firmware-custom#565]
Hi, I have problem after flashing v0.22 into classic UV-K5 the result is flashing "Release all keys". 
Any clue / advice why and what to do with that ?

**Comment by AubsUK** [comment]
I'd probably suggest re-flashing it again, as I haven't seen that before.

**Comment by hiddenvs** [comment]
> I'd probably suggest re-flashing it again, as I haven't seen that before.

Done more times, tested also with older versions, strange. Flashing went without issues, no complains. I had before running version of egzummer_v0.22 flashed there. I wanna test another firmware (fagci-mod) which was successfull, but I can't return to egzummer back. I looked over some "factory-default" firmware, downloaded one v3.1 from official Quansheng website and after flashing it, transmit doesn't work properly and speaker volume level is too low.  If I try the same file I flashed before trying another firmwares, I get only the flashing "message" as mentioned before or mishmash on display until I press some key, then the "message" appears. I am out of ideas what to do next or how to do proper factory reset to have the radio as it comes from shop.

**Comment by hiddenvs** [comment]
Update: I tried v0.16 which was successfully flashed and after that immediatelly the v0.22 which ends also successfully. So now I have v0.22 in radio, but TX is not working even is enabled. The message I get after pressing PTT is "VOLT HIGH - TX DISABLE" and Chirp doesn't read/write to radio anymore even before it was working. I am actually lost, like I don't get the behavior of the radio. It seems like it is also holding settings done via menu only till power cycle. 

I went to hidden menu and:

350 En = ON 
Tx 500 = ON 
Tx 350 = ON 
Tx 200 = ON 
F LOCK = UNLOCK ALL

TX is not working, RX speaker level is too low even FM radio is playing with normal audio level as expected also by another frequencies. K5-Prog for Windows is showing "UV-K5 Firmware, Open Edition, EGZUMER v0.22". 

Did I forget something or misuse/set something wrong ?
Thanks in advance for any advice.

**Comment by Tunas1337** [comment]
You have messed up your radio's calibration data.

If you're lucky, you have a CHIRP file saved on your computer from that radio - that contains the EEPROM, and if you take the first 0x1FFF bytes from it (the rest is a base64 signature/checksum, I'm not sure) you can flash that back with k5prog.

**Comment by egzumer** [comment]
Andrej could be right about messed up calibration, weird things happen then. If not there is some hardware issue with you particular unit, one button is stuck in on position.

**Comment by mstuckless** [comment]
I had a similar issue and it just ended up being the **_M_**(A) key that was stuck.  I kind of grabbed the key with my fingernails and pulled it out a bit.  Seems to be working now but it's something I will have to keep an eye on.  Try pressing each and everykey on the device to see if you feel the "click" that it is working before doing anything with the firmware.

**Comment by yeriel00** [comment]
Happened to me, problem was the battery was so low that it displayed the message along with random dots. The charging dock wasn't able to actually charge it enough (someone will have a better explanation for this), but i switched to usbc into the same socket and it charged and got back into the firmware.

This could be the issue for some. Not all.
