### ISSUE TITLE
Modulation is low

### ISSUE THREAD

**Issue by RoadRangerX** [egzumer/uv-k5-firmware-custom#59]
Love 0.14.1 !
I have the mic gain up full and have the TX compandor on (not convinced that helps?) but am still maybe 6dB shy of having decent modulation.
My Retevis RT-3S with the OpenGD77 firmware has 33dB of gain available past where it's about perfect  :-O
Is it possible to get more gain from the firmware?
Thanks!

**Comment by ErikS-web** [comment]
Retevis RT-3S is an other type of hardware compared to UV-K*.

**Comment by egzumer** [comment]
From what I can see in the code the Mic setting in the menu gives all that is possible.

**Comment by RoadRangerX** [comment]
I now read elsewhere that the Compandor function is broken - in fact I think it adds static and not gain. Maybe when that is fixed it will help. Or maybe I'll sus out the code and find a way to add some audio processing :)

**Comment by egzumer** [comment]
The compander is meant to be used on both radios. Transmitter compresses audio receiver expands it. If only one uses it the audio would be distorted. Also the effect is minimal.

**Comment by RoadRangerX** [comment]
I've recorded from my local repeater and do see the Tx Compandor working and doing something useful even without the Rx part.
The three sections of this graph show first another operator, then me with gain max and Tx Compandor on, then with the Compandor off.  It shows that I need about another 12dB. The Tx Compandor does add a slight amount of gain and does limit the peaks somewhat.
![PoorModulation](https://github.com/egzumer/uv-k5-firmware-custom/assets/24575272/fb756c32-0dee-41cb-807a-503646a65e8f)

**Comment by RoadRangerX** [comment]
Same graph with the last two transmissions amplified by 12 dB (in Audacity)
![PoorModulation+12](https://github.com/egzumer/uv-k5-firmware-custom/assets/24575272/54ae21e2-6344-4671-8a16-569d58269925)
