### ISSUE TITLE
Bad response header using chirp and v0.4

### ISSUE THREAD

**Issue by olonsoft** [egzumer/uv-k5-firmware-custom#6]
With release v0.4 2397e39 I can not download or upload  settings with chirp (using chirp v20230928)

Trying to download from radio, it starts and after a second
`Error communicating with radio. Bad response header`

Also trying to upload to radio 
`Error communicating with radio. Bad response header`

**Comment by lohtse** [comment]
I use chirp and compile this FW myself and no such issues at all...

**Comment by lohtse** [comment]
issue even with latest version  even when using cps

**Comment by lohtse** [comment]
ok latest commits now sorted the issue but its damn slow

**Comment by olonsoft** [comment]
I tried CPS and I get also error
`Radio parameter reading failed!`

**Comment by lohtse** [comment]
> I tried CPS and I get also error `Radio parameter reading failed!`

but you got it working with chirp lol

**Comment by egzumer** [comment]
[app/app.c line 1026](https://github.com/egzumer/uv-k5-firmware-custom/blob/main/app/app.c#L1026)

has to be changed to:
`if (gCurrentFunction == FUNCTION_TRANSMIT && (gTxTimeoutReached || gSerialConfigCountDown_500ms > 0))`

**Comment by egzumer** [comment]
ups, I just noticed these are my issues (not OneOfEleven's), I wonder why I don't get notifications about issues.

The issue comes from OneOfEleven, I just pushed a fix to my repo, will create (another) release shortly (v0.6).

**Comment by OneOfEleven** [comment]
I get them all lol
