### ISSUE TITLE
Tone Scanner Persistent Memory Issue

### ISSUE THREAD

**Issue by Egco2811** [egzumer/uv-k5-firmware-custom#618]
When I use tone scanner to save a tone using triple click to menu button for RX and TX, the tone is saved permanently. Even if I change to no tone, switching channels and then returning to the channel I cleared of the tone just reverts to the scanned tone. In conclusion I can't save the no tone to memory.

**Comment by prokrypt** [comment]
You need to [re]save the channel if you want the new tone to stick.
