### ISSUE TITLE
SSB

### ISSUE THREAD

**Issue by Big-Mal99** [egzumer/uv-k5-firmware-custom#64]
This is the only function that I personally think is missing

**Comment by troilus** [comment]
Hi #56

**Comment by egzumer** [comment]
I have no idea how to set it up. I have no antenna to receive such signals.

**Comment by Big-Mal99** [comment]
Thanks for the prompt and honest reply

**Comment by egzumer** [comment]
New modulation and programmable button function for switching modes added. If you can confirm that it works that would be nice.
[ssb.packed.bin.zip](https://github.com/egzumer/uv-k5-firmware-custom/files/13242814/ssb.packed.bin.zip)

**Comment by Big-Mal99** [comment]
Thanks for sending me this file.  I have installed it and all seems well
although at the moment I am stuggling to find a station TXing SSB to check
this function out.  I will try again tomorrow when hopefuly I may be able
to find a station.

Malcolm

**Comment by Big-Mal99** [comment]
I have had a couple of further looks at this and the problems I am having
with SSB are probably due to my loction.  I assume that v0.16 is the
released version of this test one so I am going to flash that.
Thanks for th great work
Malcolm

**Comment by egzumer** [comment]
The release have am fix disabled for ssb, should work better
