### ISSUE TITLE
TX expansion on all bands

### ISSUE THREAD

**Issue by delta1trieta** [egzumer/uv-k5-firmware-custom#68]
Para mi gusto le faltaria una opción en el menú secreto de expansión del TX en todas las bandas. Aun quedan equipos que trabajan en 80 mhz y con este walkie y su correspondiente antena se podria utilizar. Por favor tengalo en cuenta para futuras actualizaciones. Gracias por su gran trabajo.

**Comment by egzumer** [comment]
No able espaniol

**Comment by delta1trieta** [comment]
For my taste, it would lack an option in the secret menu for TX expansion in all bands. There are still devices that work at 80 MHz and with this walkie and its corresponding antenna it could be used. Please keep this in mind for future updates. Thanks for your great work.

**Comment by egzumer** [comment]
Why I'm reluctant to do that is people that didn't do the proper research. As far as I know this radio has negligible transmission power outside VHF and UHF, some microwats on some frequencies, it only transmits in FM and it has huge amount of harmonics that more often than not are transmitted on airband for example.

As an example (close to 80MHz):
<img src="https://raw.githubusercontent.com/OneOfEleven/uv-k5-firmware-custom/main/images/TX_70MHz.png" width=800 />

How is that usable?

**Comment by delta1trieta** [comment]
I assure you that with the right antenna it is enough to reach the repeaters, I already know the problem with harmonics but to be able to test the equipment they are perfect.
In fact, on a second walkie, I have another firmware installed that does transmit on all bands and I use it for that, but in general it works better with its firmware.

**Comment by IT9-TOP** [comment]
I would also like TX on all bands for testing.

**Comment by DualTachyon** [comment]
Reminder that IT9-TOP is a toxic person who doesn't think it's normal to provide details on a bug report and loves to waste developers time with non-bugs.

**Comment by IT9-TOP** [comment]
You're just good at offending people behind a keyboard, what did I do wrong? Does reporting bugs mean being toxic?
who knows which region you come from, trust a good doctor and get treated.

**Comment by DualTachyon** [comment]
You insulted us when we tried to help you. You refused to give information that was requested and demanded we figure it out for you. That's toxic behaviour.

**Comment by DualTachyon** [comment]
Not to mention the general bad attitude when you post, and harassing people on telegram.

**Comment by DualTachyon** [comment]
You didn't even apologise when we actually solved your problem while you were aggressive to us.

**Comment by IT9-TOP** [comment]
It was you who insulted me, don't tell lies, get treatment my friend you have problems.

**Comment by IT9-TOP** [comment]
Your behavior is childish, I repeat you have problems.

**Comment by DualTachyon** [comment]
Talk trash all you want. All repo owners have been warned about your toxic behaviour.

**Comment by egzumer** [comment]
I got the message thank you

**Comment by Bigpimp347** [comment]
Although under test's i find 18MHz to 30MHz to be useless, 50MHz and 70MHz show a good frequency and good RF power out, around 4w.
with correct antenna i suspect this would work well.
i also find TX 1296.000 also ok with around 1w of RF.

would it be possible to re instate 50MHz, 70MHz and 1200MHz TX ??

Also although AM and SB Demod is great, the audio is pretty poor and again no TX, 
i would be happy to be given wide TX option but no too bothered if i lose SSB and it has no TX any way.

**Comment by egzumer** [comment]
The different modulations are obtain by switching audio output type on the RF IC., and even that is undocumented feature. There is nothing to be configured to be able to change the TX modulation. At least nothing that I know of.

I guess your signal power meter doesn't show what frequency it measures, and if it is fundamental or harmonic?

**Comment by Bigpimp347** [comment]
I use a Marconi 2955 and i do have spectrum analysers to check harmonics,
surely the risk is the end user ??
not all owners and users are idiot CB radio users but some are radio amateurs with many years experience in radio, 

i was looking at the radio for us eon 4m and 6m and there is no reason to not fit external band pass filter to clean up the TX signal,
a good 4w at 70MHz and even 50MHz is worth the $20 if all i need is a good microphone (Kenwood make a great mic to fit) and suitable bpf..

**Comment by egzumer** [comment]
[tx_for_all.packed.bin.zip](https://github.com/egzumer/uv-k5-firmware-custom/files/13290711/tx_for_all.packed.bin.zip)
Go into hidden menu `F Lock`, choose `UNLOCK ALL`. It wont let you set the option. You have to repeat this action 10 times until it stays on. Do it carefully, if you confirm any other option in the process, the counter will be zeroed, and you will have do it 10 times more.

**Comment by delta1trieta** [comment]
Congratulations!!!!!! Now the firmware is great, thank you very much.

**Comment by delta1trieta** [comment]
Congratulations!!!!!! Now the firmware is much better but I see that the option (busyCL) stays on (ON) after turning the device off and on even though it is deactivated.
Is it possible to fix that option? Thank you very much in advance.

**Comment by Bigpimp347** [comment]
hidden menu F Lock ??
i have been in menu,
but not sure where to find this hidden menu,

trying to find an up to date 'owners manual' also so i can understand some
of the new features..

how do i get the hidden menu ??

**Comment by egzumer** [comment]
> option (busyCL) stays on (ON)

It does not stay on. You are trying to set it in a channel mode without saving channel settings.

**Comment by ErikS-web** [comment]
See Official release 0.17 under [Hidden Menu option 61](https://github.com/egzumer/uv-k5-firmware-custom/wiki/Menu#hidden-menu)

**Comment by ChiefRA** [comment]
Hi @egzumer ,
I've seen that even going into hidden menu `F Lock`, choose `UNLOCK ALL` still doesn't unlock the TX on the AM band: (136 - 173 range). 

How can you enable TX on AM band? 
Thanks.

**Comment by ErikS-web** [comment]
NOT.

Did you read the [Wiki ](https://github.com/egzumer/uv-k5-firmware-custom/wiki/Radio-operation#tx-on-all-bands)?

**Comment by ErikS-web** [comment]
> Hi [@egzumer](https://github.com/egzumer) , I've seen that even going into hidden menu `F Lock`, choose `UNLOCK ALL` still doesn't unlock the TX on the AM band: (136 - 173 range).
> 
> How can you enable TX on AM band? Thanks.

NOT.

Did you read the [Wiki ](https://github.com/egzumer/uv-k5-firmware-custom/wiki/Radio-operation#tx-on-all-bands)?

The radio only does FM-TX . 

On Aviation band AM-modulation is used. Don't try to use FM there.

I suggest a **TIP** and you read Closed Issues as well... Like [here's your answer,,,](https://github.com/egzumer/uv-k5-firmware-custom/issues/142)

**Comment by ChiefRA** [comment]
Thank you. I got it.
