### ISSUE TITLE
The possibility of switching the scan list using f+7

### ISSUE THREAD

**Issue by CaptainRi** [egzumer/uv-k5-firmware-custom#7]
VOX is not commonly used, can we use f+7 for toggles scanlist-1 on/off for current channel when held down

**Comment by lohtse** [comment]
> VOX is not commonly used, can we use f+7 for toggles scanlist-1 on/off for current channel when held down

or may be toggle between scanlist one and two?

**Comment by CaptainRi** [comment]
> > VOX is not commonly used, can we use f+7 for toggles scanlist-1 on/off for current channel when held down
> 
> or may be toggle between scanlist one and two?

yes

**Comment by Yag00000** [comment]
f+1 or f+2 are free !!!!

**Comment by egzumer** [comment]
Implemented by @OneOfEleven. Long press `Scan` button while scanning. Already [released](https://github.com/egzumer/uv-k5-firmware-custom/releases/tag/v0.7).
