### ISSUE TITLE
Suggestion: Can new features be added with options in the makefile.

### ISSUE THREAD

**Issue by CaptainRi** [egzumer/uv-k5-firmware-custom#75]
Suggestion: Can new features be added with options in the makefile. I found that after adding a low battery prompt and a second battery curve, the same option in the makefile will prompt for exceeding the firmware volume. So, I suggest that in the future, additional features should be provided as optional as possible. The dual battery curve is also available in the makefile for those who need it to choose from. I don't know much about programming, does this help save valuable capacity.

**Comment by egzumer** [comment]
Most of the changes are small tweaks, it is not possible to set it as options, but the memory consumption accumulates.
