### ISSUE TITLE
"RAW" and "BYPASS"？

### ISSUE THREAD

**Issue by chouyu** [egzumer/uv-k5-firmware-custom#77]
The corresponding modes for the new "RAW" and "BYPASS" modes are what?

**Comment by BG8LGP** [comment]
“RAW” is RAW demodulated signals, I think?

**Comment by egzumer** [comment]
Turn that on and play with it, you will know as much as I do.

**Comment by ErikS-web** [comment]
The parameters are for testing firmware, but do not provide intelligible audio.

With official release 0.16, these demodulation are selectable under [`Main Menu`](
https://github.com/egzumer/uv-k5-firmware-custom/wiki/Menu#main-menu)

13. `Demodu` - demodulator mode, default is FM, AM/USB can be used for listening only
