### ISSUE TITLE
Feature request: small font

### ISSUE THREAD

**Issue by TokeTokerson** [egzumer/uv-k5-firmware-custom#81]
Love this FW. Is it possible to use or have the option of using a small font so that channel name and freq can be displayed simultaneously? As is the font with the IJV firmware. Looks nice and tidy. ![image](https://github.com/egzumer/uv-k5-firmware-custom/assets/148666132/61c78e16-5ea4-43c4-8c86-198215f8a012)

**Comment by egzumer** [comment]
You can display name and freq simultaneously.
