### ISSUE TITLE
Squelsh stays closed when D Decd is set to ON

### ISSUE THREAD

**Issue by krotoniec** [egzumer/uv-k5-firmware-custom#88]
Hi guys, I noticed some strange behavior. As soon as I will turn D Decd to ON (Menu 53), squelsh stays closed upon RX and I'm unable to receive transmissions anymore. In monitor mode RX works fine despite D Decd being set.

I'm using firmware a0c2181

**Comment by DualTachyon** [comment]
When using D-DEC is enabled, only DTMF calls will open squelch.

**Comment by egzumer** [comment]
RTFM (fine)
https://github.com/egzumer/uv-k5-firmware-custom/wiki/Radio-operation#dtmf-calling-decoding
