### ISSUE TITLE
F-lock  menu seems broken

### ISSUE THREAD

**Issue by lohtse** [egzumer/uv-k5-firmware-custom#91]
After latest Commits .. When I set F-lock to unlock all    it always defaults  too 144-148    420-450 or what ever else may have been chosen to check, .... It used to work ok on previous builds....

TX does still work on all  just the Menus does not show the actual change to the setting..

**Comment by egzumer** [comment]
This is on purpose. It didn't used to work on previous builds because it wasn't there. TX doesn't work on all, does it TX on 80MHz or 1200MHz?

Before I make a release I'll add necessary manual to the wiki.

**Comment by egzumer** [comment]
There was never "unlock all(or similar". 
I changed some names long time ago, and did some modifications now, that is it.
It certainly won't TX on 84-86mh
It also didn't work on any previous builds.

**Comment by egzumer** [comment]
I already made myself clear.

**Comment by egzumer** [comment]
What is the `F Lock` set on?

**Comment by egzumer** [comment]
Attach config dump from the radio if you can.

**Comment by egzumer** [comment]
No comment 🙄

https://github.com/egzumer/uv-k5-firmware-custom/assets/14902414/f5a99bcd-b657-475b-a1a7-a33e2bdbb356

**Comment by egzumer** [comment]
Are you a sane person?
What did I tell you? This is on purpose, before I make a release I'll add necessary manual to the wiki.
You said that you can transmit on 84-86mhz, regardless.
I asked what is the F Lock set on.

**Comment by egzumer** [comment]
I explained to you everything as clear as I could, but you decided to be a smartass, just like the last time. I don't act as an asshole to people that are not assholes to me (at least I try not to).

I know you will find some excuse, so let's not continue this conversation. I'm fine with you not rising any issues again.
