### ISSUE TITLE
Request for New updates

### ISSUE THREAD

**Issue by Zahurzahur** [egzumer/uv-k5-firmware-custom#93]
Sir
I have no any coputer to cpmpile new updates. I have installed FW through flash browser so kindly uploaded your new acheavment soon.
I will be very thankful to you.

**Comment by egzumer** [comment]
Current built files for each commit are now available in https://github.com/egzumer/uv-k5-firmware-custom/actions on the bottom.
Releases come out when they come out. Next one is due for today.

**Comment by Zahurzahur** [comment]
So nice of you.
