### ISSUE TITLE
Full range transmission

### ISSUE THREAD

**Issue by UW5EOT** [egzumer/uv-k5-firmware-custom#97]
After selecting “UNLOCK_ALL” ten times in the “F_lock” menu, it was possible to select “UNLOCK_ALL”, but still the transmission on the entire range is not unlocked. (egzumer_v0.17.packed.bin)

**Comment by egzumer** [comment]
Read the manual.
https://github.com/egzumer/uv-k5-firmware-custom/wiki/Radio-operation#tx-on-all-bands

**Comment by egzumer** [comment]
What frequency does it not unlock?

**Comment by UW5EOT** [comment]
When selecting "Unlock All" It did not work, for example, at 18,000
MHz, at 100,000 MHz. But in the morning when we updated the firmware
everything worked as it should. Thank you very much!


чт, 9 нояб. 2023 г., 13:00 egzumer ***@***.***>:
