### ISSUE TITLE
Scanner in frequency mode enters range unsupported by hardware (630-840 MHz).

### ISSUE THREAD

**Issue by crazy4volvo** [egzumer/uv-k5-firmware-custom#99]
Steps to reproduce:
-set vfo to freq mode
-enter frequency 630000 or 840000
-start scanning (change direction in case of 840Mhz)

**Comment by egzumer** [comment]
There is no downside to this and it would be too complicated trying to mitigate this. Also it looks like it does receive in this range, I've been even asked to unlock this range in VFO.
